import Link from 'next/link'; import { headers } from 'next/headers'; import { db } from '@/lib/prisma'; import { getCurrentUser } from '@/lib/auth'; import { consumeRateLimit } from '@/lib/rate-limit'; import { clientIp } from '@/lib/request-ip'; import { notFound, redirect } from 'next/navigation'; import { money } from '@/lib/config'; import { Footer } from '@/components/footer'; import CancelOrderButton from '@/components/cancel-order-button'; import RequestReturn from '@/components/request-return'; import { alreadyReturnedQuantities } from '@/lib/returns';
export default async function OrderDetails({params,searchParams}:{params:Promise<{orderNumber:string}>;searchParams:Promise<{email?:string}>}){const user=await getCurrentUser();const {orderNumber}=await params;const {email:emailParam}=await searchParams;const order=await db.order.findUnique({where:{orderNumber},select:{id:true,orderNumber:true,userId:true,email:true,createdAt:true,status:true,shippingAddressJson:true,paymentMethod:true,paymentStatus:true,shippingTotal:true,subtotal:true,grandTotal:true,currency:true,trackingNumber:true,items:{select:{id:true,name:true,quantity:true,totalPrice:true},},events:{select:{id:true,status:true,message:true,createdAt:true},orderBy:{createdAt:'asc'}},paymentTransactions:{select:{id:true,status:true,amount:true},orderBy:{createdAt:'desc'}}}});
  if(!order){if(!user)redirect('/orders/lookup');return notFound()}
  const isOwner=Boolean(user&&order.userId===user.id)
  let guestVerified=false
  if(!isOwner&&emailParam){const ip=clientIp(await headers());const limit=consumeRateLimit(`order-guest-view:ip:${ip}`,20,15*60*1000);if(limit.allowed&&order.email.trim().toLowerCase()===emailParam.trim().toLowerCase())guestVerified=true}
  if(!isOwner&&!guestVerified){if(user)return notFound();redirect('/orders/lookup')}
  const tracking=order.status==='PROCESSING'||order.status==='SHIPPED'?await db.deliveryTracking.findUnique({where:{orderId:order.id},select:{trackingToken:true,active:true}}):null;let address:any={};try{address=JSON.parse(order.shippingAddressJson)}catch{};const refundable=order.paymentTransactions.filter(t=>t.status==='refunded').reduce((s,t)=>s+t.amount,0)
  const returnable=isOwner&&['SHIPPED','DELIVERED'].includes(order.status)
  const returnRequests=isOwner?await db.returnRequest.findMany({where:{orderId:order.id},include:{items:true},orderBy:{createdAt:'desc'}}):[]
  const alreadyReturned=returnable?await alreadyReturnedQuantities(db,order.id,order.orderNumber):new Map<string,number>()
  const returnableItems=order.items.map(i=>({id:i.id,name:i.name,quantity:i.quantity,remaining:returnable?Math.max(0,i.quantity-(alreadyReturned.get(i.id)||0)):0}))
  return <><main className="section"><div className="container"><Link className="textLink" href={isOwner?'/account':'/orders/lookup'}>← {isOwner?'Back to account':'Look up another order'}</Link><div className="sectionHead"><div><span className="muted">ORDER</span><h1 className="h2">#{order.orderNumber}</h1><p className="muted">{order.createdAt.toLocaleString()}</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span className="pill">{order.status}</span>{isOwner&&(order.status==='PENDING'||order.status==='CONFIRMED')&&<CancelOrderButton orderNumber={order.orderNumber}/>}</div></div>{tracking?.active&&<div className="card" style={{padding:18,marginBottom:12,display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><strong>Your delivery is live</strong><p className="muted" style={{margin:4}}>See the courier's approximate position and latest ETA.</p></div><Link className="btn" href={`/track/${tracking.trackingToken}`}>Track delivery</Link></div>}<div className="grid twoColumn"><section><div className="card" style={{padding:20}}><h3>Items</h3>{order.items.map(i=><div className="summaryLine" key={i.id}><span>{i.name} × {i.quantity}</span><strong>{money(i.totalPrice,order.currency)}</strong></div>)}<div className="summaryLine"><span>Subtotal</span><strong>{money(order.subtotal,order.currency)}</strong></div><div className="summaryLine"><span>Shipping</span><strong>{money(order.shippingTotal,order.currency)}</strong></div><div className="summaryLine total"><span>Total</span><strong>{money(order.grandTotal,order.currency)}</strong></div>{refundable>0&&<p className="muted" style={{marginTop:10}}>Refunded so far: {money(refundable,order.currency)}</p>}</div><div className="card" style={{padding:20,marginTop:12}}><h3>Timeline</h3>{order.events.map(e=><div className="timelineItem" key={e.id}><span className="dot"/><div><strong>{e.status}</strong><p className="muted">{e.message}</p><small className="muted">{e.createdAt.toLocaleString()}</small></div></div>)}</div>{isOwner&&(returnable||returnRequests.length>0)&&<RequestReturn orderNumber={order.orderNumber} items={returnableItems} returns={JSON.parse(JSON.stringify(returnRequests))}/>}</section><aside className="card" style={{padding:20,height:'fit-content'}}><h3>Delivery</h3><p className="muted">{address.firstName||''} {address.lastName||''}<br/>{address.line1||''}{address.line2?<><br/>{address.line2}</>:null}<br/>{address.city||''}{address.region?`, ${address.region}`:''}<br/>{address.country||''}</p><h3>Payment</h3><p className="muted">{order.paymentMethod} · {order.paymentStatus}</p>{order.trackingNumber&&<><h3>Tracking</h3><p>{order.trackingNumber}</p></>}</aside></div></div></main><Footer/></>}
