import { db } from '@/lib/prisma'; import { requirePermission } from '@/lib/auth'; import { audit } from '@/lib/audit'; import { json } from '@/lib/utils'
// Only these two types are actually rendered on the storefront homepage (see
// components/aliexpress-home.tsx) -- restricted here too so a request that bypasses the admin
// UI's own picker can't create a block that silently does nothing either.
const RENDERED_TYPES = new Set(['announcement', 'trust'])
export async function GET(){try{await requirePermission('content.view');return json(await db.homepageBlock.findMany({orderBy:{sortOrder:'asc'}}))}catch(e){return json({error:e instanceof Error?e.message:'Forbidden'},{status:403})}}
export async function POST(req:Request){try{const actor=await requirePermission('content.manage');const b=await req.json();const type=String(b.type||'');if(!RENDERED_TYPES.has(type))return json({error:'Type must be "announcement" or "trust" -- these are the only block types the storefront renders'},{status:400});const block=await db.homepageBlock.create({data:{type,title:b.title?String(b.title):null,subtitle:b.subtitle?String(b.subtitle):null,contentJson:typeof b.contentJson==='string'?b.contentJson:JSON.stringify(b.contentJson||{}),isActive:b.isActive!==false,sortOrder:Number(b.sortOrder)||0}});await audit(actor.id,'homepage.created','HomepageBlock',block.id,{type:block.type});return json({block},{status:201})}catch(e){return json({error:e instanceof Error?e.message:'Unable to create block'},{status:400})}}
export async function PATCH(req:Request){try{const actor=await requirePermission('content.manage');const b=await req.json();if(b.type!==undefined&&!RENDERED_TYPES.has(String(b.type)))return json({error:'Type must be "announcement" or "trust" -- these are the only block types the storefront renders'},{status:400});const block=await db.homepageBlock.update({where:{id:String(b.id)},data:{...(b.type!==undefined?{type:String(b.type)}:{}),...(b.title!==undefined?{title:String(b.title||'')||null}:{}),...(b.subtitle!==undefined?{subtitle:String(b.subtitle||'')||null}:{}),...(b.contentJson!==undefined?{contentJson:typeof b.contentJson==='string'?b.contentJson:JSON.stringify(b.contentJson)}:{}),...(b.isActive!==undefined?{isActive:Boolean(b.isActive)}:{}),...(b.sortOrder!==undefined?{sortOrder:Number(b.sortOrder)||0}:{})}});await audit(actor.id,'homepage.updated','HomepageBlock',block.id,b);return json({block})}catch(e){return json({error:e instanceof Error?e.message:'Unable to update block'},{status:400})}}
export async function DELETE(req:Request){try{const actor=await requirePermission('content.manage');const id=new URL(req.url).searchParams.get('id');if(!id)return json({error:'Block id required'},{status:400});const existing=await db.homepageBlock.findUnique({where:{id}});if(!existing)return json({error:'Content block not found'},{status:404});await db.homepageBlock.delete({where:{id}});await audit(actor.id,'homepage.deleted','HomepageBlock',id,{type:existing.type,title:existing.title});return json({ok:true})}catch(e){return json({error:e instanceof Error?e.message:'Unable to delete block'},{status:400})}}
