services:
  - type: web
    name: ecommerce-pro-v7
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node -v && npm start
    initialDeployCommand: npm run db:seed
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22.23.2
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-pro-db
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: CRON_SECRET
        generateValue: true
      - key: PAYMENT_WEBHOOK_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: PASSWORD_RESET_EMAIL_WEBHOOK_URL
        sync: false
      - key: PASSWORD_RESET_EMAIL_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_BRAND_NAME
        value: Your Brand
      - key: NEXT_PUBLIC_CURRENCY
        value: USD
      - key: NEXT_PUBLIC_COUNTRY
        value: Lebanon
      - key: NEXT_PUBLIC_LOCALE
        value: en-US
      - key: NEXT_PUBLIC_WHATSAPP_NUMBER
        value: ""
      - key: SEED_ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: PAYMENT_PROVIDER
        value: manual

databases:
  - name: ecommerce-pro-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "16"
