import { db } from '@/lib/prisma'
import { requirePermission } from '@/lib/auth'
import { audit } from '@/lib/audit'

const MAX_ROWS = 10000
const TYPES = new Set(['orders', 'customers', 'products', 'categories', 'collections'])
type Row = Array<string | number | boolean | null | Date | undefined>
function csvCell(value: Row[number]) { if (value == null) return ''; const raw=value instanceof Date?value.toISOString():String(value); const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw; return /[",\r\n]/.test(safe)?`"${safe.replace(/"/g,'""')}"`:safe }
function csv(headers:string[], rows:Row[]){return [headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\r\n')+'\r\n'}
function unauthorized(error:unknown){if(error instanceof Error&&error.message==='UNAUTHORIZED')return Response.json({error:'Unauthorized'},{status:401});if(error instanceof Error&&error.message==='FORBIDDEN')return Response.json({error:'Forbidden'},{status:403});return null}

export async function GET(req:Request){
 let actor:Awaited<ReturnType<typeof requirePermission>>; try{actor=await requirePermission('reports.view')}catch(e){return unauthorized(e)||Response.json({error:'Unable to authorize export'},{status:500})}
 const url=new URL(req.url), type=url.searchParams.get('type')?.trim().toLowerCase()||''; if(!TYPES.has(type))return Response.json({error:'type must be orders, customers, products, categories, or collections'},{status:400})
 const ids=url.searchParams.getAll('id').filter(Boolean); const categoryId=url.searchParams.get('categoryId'); const collectionId=url.searchParams.get('collectionId')
 try{
  let headers:string[]=[]; let rows:Row[]=[]
  if(type==='products'){
   const data=await db.product.findMany({where:{...(ids.length?{id:{in:ids}}:{}),...(categoryId?{categoryId}:{}),...(collectionId?{collections:{some:{collectionId}}}:{})},take:MAX_ROWS,orderBy:{name:'asc'},select:{id:true,name:true,slug:true,brand:true,vendor:true,productType:true,basePrice:true,compareAtPrice:true,costPrice:true,sku:true,barcode:true,status:true,featured:true,requiresShipping:true,taxable:true,trackInventory:true,continueSellingWhenOutOfStock:true,category:{select:{slug:true,name:true}},collections:{select:{collection:{select:{slug:true}}}},createdAt:true,updatedAt:true}})
   headers=['id','name','slug','brand','vendor','product_type','base_price','compare_at_price','cost_price','sku','barcode','status','featured','requires_shipping','taxable','track_inventory','continue_selling_when_out_of_stock','category_slug','category','collection_slugs','created_at','updated_at']; rows=data.map(p=>[p.id,p.name,p.slug,p.brand,p.vendor,p.productType,p.basePrice,p.compareAtPrice,p.costPrice,p.sku,p.barcode,p.status,p.featured,p.requiresShipping,p.taxable,p.trackInventory,p.continueSellingWhenOutOfStock,p.category?.slug,p.category?.name,p.collections.map(c=>c.collection.slug).join('|'),p.createdAt,p.updatedAt])
  } else if(type==='categories'){const data=await db.category.findMany({where:ids.length?{id:{in:ids}}:{},take:MAX_ROWS,orderBy:{name:'asc'},select:{id:true,name:true,slug:true,description:true,imageUrl:true,isActive:true,sortOrder:true,parentId:true,parent:{select:{slug:true}},createdAt:true,updatedAt:true}}); headers=['id','name','slug','description','image_url','is_active','sort_order','parent_id','parent_slug','created_at','updated_at']; rows=data.map(c=>[c.id,c.name,c.slug,c.description,c.imageUrl,c.isActive,c.sortOrder,c.parentId,c.parent?.slug,c.createdAt,c.updatedAt])
  } else if(type==='collections'){const data=await db.collection.findMany({where:ids.length?{id:{in:ids}}:{},take:MAX_ROWS,orderBy:{name:'asc'},select:{id:true,name:true,slug:true,description:true,imageUrl:true,isActive:true,sortOrder:true,createdAt:true,updatedAt:true}}); headers=['id','name','slug','description','image_url','is_active','sort_order','created_at','updated_at']; rows=data.map(c=>[c.id,c.name,c.slug,c.description,c.imageUrl,c.isActive,c.sortOrder,c.createdAt,c.updatedAt])
  } else if(type==='orders'){const data=await db.order.findMany({take:MAX_ROWS,orderBy:{createdAt:'desc'},select:{orderNumber:true,email:true,phone:true,subtotal:true,discountTotal:true,shippingTotal:true,taxTotal:true,grandTotal:true,currency:true,status:true,paymentStatus:true,fulfillmentStatus:true,paymentMethod:true,couponCode:true,shippingMethod:true,createdAt:true,updatedAt:true}}); headers=['order_number','email','phone','subtotal','discount_total','shipping_total','tax_total','grand_total','currency','status','payment_status','fulfillment_status','payment_method','coupon_code','shipping_method','created_at','updated_at']; rows=data.map(o=>[o.orderNumber,o.email,o.phone,o.subtotal,o.discountTotal,o.shippingTotal,o.taxTotal,o.grandTotal,o.currency,o.status,o.paymentStatus,o.fulfillmentStatus,o.paymentMethod,o.couponCode,o.shippingMethod,o.createdAt,o.updatedAt])
  } else {const data=await db.user.findMany({where:{role:'CUSTOMER'},take:MAX_ROWS,orderBy:{createdAt:'desc'},select:{id:true,name:true,email:true,phone:true,isActive:true,emailVerifiedAt:true,lastLoginAt:true,createdAt:true,updatedAt:true}}); headers=['id','name','email','phone','is_active','email_verified_at','last_login_at','created_at','updated_at']; rows=data.map(u=>[u.id,u.name,u.email,u.phone,u.isActive,u.emailVerifiedAt,u.lastLoginAt,u.createdAt,u.updatedAt])}
  await audit(actor.id,'admin.data_exported','Export',type,{type,rows:rows.length,filters:{ids:ids.length,categoryId,collectionId},maxRows:MAX_ROWS})
  return new Response(csv(headers,rows),{status:200,headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="ecommerce-pro-${type}-${new Date().toISOString().slice(0,10)}.csv"`,'Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff'}})
 }catch(e){console.error('[admin/exports] failed',e);return Response.json({error:'Unable to generate export'},{status:500})}
}
