'use client'

import { Download, Upload, FileSpreadsheet } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import styles from './admin-data-transfer.module.css'
import ui from './admin-ui.module.css'

type Option={id:string;name:string;sku?:string}
type Resource='products'|'categories'|'collections'

export default function AdminDataTransfer({canImport=false}:{canImport?:boolean}){
 const inputRef=useRef<HTMLInputElement>(null); const [resource,setResource]=useState<Resource>('products'); const [products,setProducts]=useState<Option[]>([]); const [categories,setCategories]=useState<Option[]>([]); const [collections,setCollections]=useState<Option[]>([]); const [selected,setSelected]=useState<string[]>([]); const [categoryId,setCategoryId]=useState(''); const [collectionId,setCollectionId]=useState(''); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [preview,setPreview]=useState<any[]>([])
 useEffect(()=>{fetch('/api/admin/exports/options',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{setProducts(d.products||[]);setCategories(d.categories||[]);setCollections(d.collections||[])}).catch(()=>setError('Unable to load transfer options.'))},[])
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 function reset(){setSelected([]);setCategoryId('');setCollectionId('');setPreview([]);setMessage('');setError('')}
 async function download(){setBusy('export');setMessage('');setError('');try{const p=new URLSearchParams({type:resource});selected.forEach(id=>p.append('id',id));if(resource==='products'&&categoryId)p.set('categoryId',categoryId);if(resource==='products'&&collectionId)p.set('collectionId',collectionId);const r=await fetch(`/api/admin/exports?${p}`,{cache:'no-store'});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Export failed');const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`ecommerce-pro-${resource}.csv`;a.click();URL.revokeObjectURL(u);setMessage(`${resource} exported successfully.`)}catch(e){setError(e instanceof Error?e.message:'Export failed')}finally{setBusy('')}}
 async function importFile(file:File){setBusy('preview');setMessage('');setError('');try{const form=new FormData();form.append('file',file);const r=await fetch(`/api/admin/imports?type=${resource}&mode=preview`,{method:'POST',body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Validation failed');setPreview(d.rows||[]);if(d.errors?.length)setError(d.errors.join(' • '));else setMessage(`Validated ${d.rows?.length||0} rows. Review and apply the import.`)}catch(e){setError(e instanceof Error?e.message:'Validation failed')}finally{setBusy('')}}
 async function apply(){const file=inputRef.current?.files?.[0];if(!file)return;setBusy('import');setMessage('');setError('');try{const form=new FormData();form.append('file',file);const r=await fetch(`/api/admin/imports?type=${resource}&mode=apply`,{method:'POST',body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Import failed');setMessage(`${resource} imported: ${d.created||0} created, ${d.updated||0} updated.`);setPreview([]);if(inputRef.current)inputRef.current.value=''}catch(e){setError(e instanceof Error?e.message:'Import failed')}finally{setBusy('')}}
 const choices=resource==='products'?products:resource==='categories'?categories:collections
 return <section className={ui.card} style={{padding:18,marginBottom:18}}><div style={{display:'flex',alignItems:'center',gap:11,marginBottom:14}}><div className={styles.icon}><FileSpreadsheet size={18}/></div><div><strong style={{display:'block'}}>Data transfer</strong><span className={ui.muted} style={{fontSize:12}}>Scoped CSV import/export for products, categories and collections.</span></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><label><span className={ui.muted}>Data type</span><select className={ui.select} value={resource} onChange={e=>{setResource(e.target.value as Resource);reset()}}><option value="products">Products</option><option value="categories">Categories</option><option value="collections">Collections</option></select></label>{resource==='products'&&<><label><span className={ui.muted}>Category</span><select className={ui.select} value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className={ui.muted}>Collection</span><select className={ui.select} value={collectionId} onChange={e=>setCollectionId(e.target.value)}><option value="">All collections</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}</div>
 <div className={styles.checklist}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><span className={ui.muted}>Select specific {resource} ({selected.length})</span><button type="button" className={`${ui.btn} ${ui.btnSecondary}`} onClick={()=>setSelected(selected.length===choices.length?[]:choices.map(x=>x.id))}>{selected.length===choices.length?'Clear all':'Select all'}</button></div>{choices.map(x=><label key={x.id} style={{display:'flex',gap:8,alignItems:'center',padding:'6px 2px'}}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/><span>{x.name}</span>{x.sku&&<span className={ui.muted}>{x.sku}</span>}</label>)}</div>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button type="button" className={`${ui.btn} ${ui.btnSecondary}`} onClick={()=>void download()} disabled={!!busy}><Download size={15}/>Export {selected.length?'selected':'filtered'} {resource}</button>{canImport&&<><input ref={inputRef} type="file" accept=".csv,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f)}}/><button type="button" className={ui.btn} onClick={()=>inputRef.current?.click()} disabled={!!busy}><Upload size={15}/>Import {resource}</button>{preview.length>0&&<button type="button" className={`${ui.btn} ${ui.btnSecondary}`} onClick={()=>void apply()} disabled={busy==='import'}>{busy==='import'?'Importing…':'Apply import'}</button>}</>}</div>
 {preview.length>0&&<div className={ui.muted} style={{marginTop:10,fontSize:12}}>Preview: {preview.length} rows ready to import.</div>}{message&&<div className={ui.alert} style={{marginTop:12,marginBottom:0}}>{message}</div>}{error&&<div className={`${ui.alert} ${ui.alertDanger}`} style={{marginTop:12,marginBottom:0}}>{error}</div>}
 </section>
}
