'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Globe2, Monitor, Smartphone, Tablet, RefreshCw, Users, MapPin, Clock3, ExternalLink, LocateFixed, Search, Pause, Play, X, Navigation, type LucideIcon } from 'lucide-react'

type Visitor = {
  sessionId: string; userId: string | null; name: string | null; path: string; country: string | null; city: string | null; region: string | null
  latitude: number | null; longitude: number | null; device: string | null; browser: string | null; os: string | null; referrer: string | null
  firstSeenAt: string; lastSeenAt: string
}

function relativeTime(iso: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 1000)); if (seconds < 10) return 'just now'; if (seconds < 60) return `${seconds}s ago`; const minutes = Math.floor(seconds / 60); return `${minutes}m ago` }
function DeviceIcon({ device }: { device: string | null }) { if (device === 'mobile') return <Smartphone size={16} />; if (device === 'tablet') return <Tablet size={16} />; return <Monitor size={16} /> }
function locationLabel(v: Visitor) { return [v.city, v.region, v.country].filter(Boolean).join(', ') || 'Location unavailable' }

function MapPanel({ visitors, selectedId, onSelect }: { visitors: Visitor[]; selectedId: string | null; onSelect: (id: string) => void }) {
  const located = visitors.filter(v => Number.isFinite(v.latitude) && Number.isFinite(v.longitude))
  return <div className="relative min-h-[430px] overflow-hidden rounded-3xl border bg-[radial-gradient(circle_at_50%_40%,rgba(99,102,241,.10),transparent_42%),linear-gradient(180deg,#f8fafc,#eef2f7)] dark:bg-[radial-gradient(circle_at_50%_40%,rgba(99,102,241,.16),transparent_42%),linear-gradient(180deg,#111827,#0f172a)]">
    <div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(100,116,139,.18)_1px,transparent_1px),linear-gradient(90deg,rgba(100,116,139,.18)_1px,transparent_1px)] [background-size:48px_48px]" />
    <div className="absolute inset-x-12 top-1/2 border-t border-dashed opacity-30" /><div className="absolute left-1/2 top-10 bottom-10 border-l border-dashed opacity-30" />
    {located.map(v => { const left = Math.max(3, Math.min(97, ((v.longitude! + 180) / 360) * 100)); const top = Math.max(8, Math.min(92, ((90 - v.latitude!) / 180) * 100)); const selected = v.sessionId === selectedId; return <button key={v.sessionId} type="button" onClick={() => onSelect(v.sessionId)} className="absolute -translate-x-1/2 -translate-y-1/2 outline-none" style={{ left: `${left}%`, top: `${top}%` }} title={`${v.name || 'Anonymous visitor'} · ${locationLabel(v)}`} aria-label={`Select ${v.name || 'anonymous visitor'}`}><span className={`absolute -inset-2 rounded-full ${selected ? 'animate-ping bg-primary/30' : 'bg-emerald-500/20'}`} /><span className={`relative flex h-5 w-5 items-center justify-center rounded-full border-2 border-white shadow-lg transition-transform ${selected ? 'scale-125 bg-primary' : 'bg-emerald-500'}`}><span className="h-1.5 w-1.5 rounded-full bg-white" /></span></button> })}
    <div className="absolute left-4 top-4 flex items-center gap-2 rounded-xl border bg-background/90 px-3 py-2 text-xs font-semibold shadow-sm backdrop-blur"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />Live visitor map</div>
    <div className="absolute right-4 top-4 rounded-xl border bg-background/90 px-3 py-2 text-[11px] shadow-sm backdrop-blur"><span className="inline-flex items-center gap-1.5"><LocateFixed size={13} />{located.length} precise</span></div>
    <div className="absolute bottom-4 left-4 right-4 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-xl rounded-xl border bg-background/90 px-3 py-2 text-xs shadow-sm backdrop-blur">{located.length ? 'Select a marker to inspect the active session. Precise coordinates are available only after browser location consent.' : 'No active visitors have shared precise coordinates yet.'}</div><div className="rounded-xl border bg-background/90 px-3 py-2 text-[11px] text-muted-foreground shadow-sm backdrop-blur">Approximate city/country data can still appear without precise consent.</div></div>
  </div>
}

export default function LiveVisitorsAdmin() {
  const [visitors, setVisitors] = useState<Visitor[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [lastUpdated, setLastUpdated] = useState<Date | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [query, setQuery] = useState(''); const [autoRefresh, setAutoRefresh] = useState(true)
  const load = useCallback(async () => { try { setError(''); const response = await fetch('/api/admin/live-visitors', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Unable to load live visitors'); setVisitors(data.visitors || []); setLastUpdated(new Date()); setSelectedId(current => current && (data.visitors || []).some((v: Visitor) => v.sessionId === current) ? current : null) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load live visitors') } finally { setLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  useEffect(() => { if (!autoRefresh) return; const timer = window.setInterval(load, 15_000); return () => window.clearInterval(timer) }, [autoRefresh, load])
  const countries = useMemo(() => new Set(visitors.map(v => v.country).filter(Boolean)).size, [visitors]); const precise = useMemo(() => visitors.filter(v => Number.isFinite(v.latitude) && Number.isFinite(v.longitude)).length, [visitors])
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return visitors; return visitors.filter(v => [v.name, v.path, v.country, v.city, v.region, v.device, v.browser, v.os].filter(Boolean).some(value => String(value).toLowerCase().includes(q))) }, [query, visitors])
  const selected = visitors.find(v => v.sessionId === selectedId) || null
  const stats: Array<{ label: string; value: string | number; Icon: LucideIcon; hint?: string }> = [{ label: 'Active visitors', value: visitors.length, Icon: Users, hint: 'online now' }, { label: 'Locations', value: countries, Icon: Globe2, hint: 'countries / regions' }, { label: 'Precise locations', value: precise, Icon: LocateFixed, hint: 'consented' }, { label: 'Last refresh', value: lastUpdated ? lastUpdated.toLocaleTimeString() : '—', Icon: Clock3, hint: autoRefresh ? 'auto · 15s' : 'paused' }]
  return <section className="mt-10 space-y-5">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border bg-background px-2.5 py-1 text-xs font-semibold text-emerald-600 shadow-sm"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-500" />LIVE</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Visitors right now</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Monitor active storefront sessions in real time. Sessions expire after 90 seconds of inactivity.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => setAutoRefresh(v => !v)} className="inline-flex h-10 items-center gap-2 rounded-lg border bg-background px-3 text-sm font-medium shadow-sm hover:bg-muted">{autoRefresh ? <Pause size={15} /> : <Play size={15} />}{autoRefresh ? 'Pause live' : 'Resume live'}</button><button type="button" onClick={load} disabled={loading} className="inline-flex h-10 items-center gap-2 rounded-lg border bg-background px-3 text-sm font-medium shadow-sm hover:bg-muted disabled:opacity-50"><RefreshCw size={15} className={loading ? 'animate-spin' : ''} />Refresh</button></div></div>
    {error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, Icon, hint }) => <div key={label} className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex items-center justify-between text-muted-foreground"><span className="text-sm">{label}</span><Icon size={17} /></div><div className="mt-2 flex items-baseline gap-2"><span className="text-2xl font-semibold tracking-tight">{value}</span><span className="text-[11px] text-muted-foreground">{hint}</span></div></div>)}</div>
    <MapPanel visitors={visitors} selectedId={selectedId} onSelect={setSelectedId} />
    <div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Active sessions <span className="ml-1 text-muted-foreground">({filtered.length})</span></h3><p className="mt-1 text-xs text-muted-foreground">Precise coordinates are displayed only after explicit browser location permission.</p></div><div className="relative w-full sm:w-64"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search visitor, page, city…" className="h-9 w-full rounded-lg border bg-background pl-9 pr-3 text-sm outline-none ring-offset-background placeholder:text-muted-foreground focus:ring-2 focus:ring-ring" /></div></div>
      {filtered.length === 0 ? <div className="p-12 text-center"><Users className="mx-auto text-muted-foreground/50" size={28} /><p className="mt-3 text-sm font-medium">{visitors.length ? 'No matching sessions' : 'No active storefront visitors'}</p><p className="mt-1 text-xs text-muted-foreground">{visitors.length ? 'Try a different search.' : 'Open the storefront in another browser or device to test live tracking.'}</p></div> : <div className="divide-y">{filtered.map(v => { const preciseLocation = Number.isFinite(v.latitude) && Number.isFinite(v.longitude); const active = v.sessionId === selectedId; return <button key={v.sessionId} type="button" onClick={() => setSelectedId(v.sessionId === selectedId ? null : v.sessionId)} className={`grid w-full gap-3 px-5 py-4 text-left transition-colors hover:bg-muted/50 md:grid-cols-[1.4fr_1.25fr_1fr_auto] md:items-center ${active ? 'bg-muted/40' : ''}`}><div className="min-w-0"><div className="flex items-center gap-2 font-medium"><span className={`h-2 w-2 shrink-0 rounded-full ${preciseLocation ? 'bg-emerald-500' : 'bg-sky-500'}`} />{v.name || 'Anonymous visitor'}</div><div className="mt-1 flex items-center gap-1.5 truncate text-xs text-muted-foreground"><span className="truncate">{v.path}</span></div></div><div className="flex min-w-0 items-center gap-2 text-sm"><MapPin size={15} className="shrink-0 text-muted-foreground" /><span className="truncate">{locationLabel(v)}</span><span className="shrink-0 text-[10px] text-muted-foreground">{preciseLocation ? 'precise' : 'approx.'}</span></div><div className="flex items-center gap-2 text-sm text-muted-foreground"><DeviceIcon device={v.device} /><span className="truncate">{[v.browser, v.os].filter(Boolean).join(' · ') || 'Unknown device'}</span></div><div className="flex items-center justify-end gap-2 text-xs text-muted-foreground">{preciseLocation && <span className="hidden items-center gap-1 rounded-md border px-2 py-1 sm:inline-flex"><Navigation size={12} /> Map</span>}{relativeTime(v.lastSeenAt)}</div></button> })}</div>}
    </div>
    {selected && <div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-semibold"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />Selected visitor</div><h3 className="mt-2 text-lg font-semibold">{selected.name || 'Anonymous visitor'}</h3><p className="mt-1 text-xs text-muted-foreground">Session {selected.sessionId}</p></div><button type="button" onClick={() => setSelectedId(null)} className="rounded-lg border p-2 hover:bg-muted" aria-label="Close visitor details"><X size={16} /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Current page</div><div className="mt-1 truncate text-sm">{selected.path}</div></div><div><div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Location</div><div className="mt-1 text-sm">{locationLabel(selected)}</div></div><div><div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Device</div><div className="mt-1 text-sm">{[selected.device, selected.browser, selected.os].filter(Boolean).join(' · ') || 'Unknown'}</div></div><div><div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">First seen</div><div className="mt-1 text-sm">{new Date(selected.firstSeenAt).toLocaleTimeString()}</div></div></div>{Number.isFinite(selected.latitude) && Number.isFinite(selected.longitude) && <div className="mt-5 flex flex-wrap items-center gap-2"><a href={`https://www.google.com/maps?q=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-medium text-primary-foreground hover:opacity-90"><ExternalLink size={14} />Open precise location</a><span className="text-xs text-muted-foreground">Coordinates are consented by the visitor.</span></div>}</div>}
    <p className="px-1 text-[11px] leading-5 text-muted-foreground">Privacy: precise coordinates are collected only after browser permission. Without consent, the dashboard can display only the approximate location data available to the application. Live sessions automatically expire after inactivity.</p>
  </section>
}
