'use client'
import { useState } from 'react'
import { Code2, Plus, Trash2 } from 'lucide-react'

type Definition={id:string;namespace:string;key:string;name:string;description?:string|null;type:string;ownerType:string;isList:boolean}
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{'content-type':'application/json',...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}

export default function MetafieldsAdmin({initial}:{initial:Definition[]}){
 const [rows,setRows]=useState(initial),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState({namespace:'custom',key:'',name:'',description:'',type:'single_line_text_field',ownerType:'PRODUCT',isList:false})
 async function refresh(){const d=await api('/api/admin/metafields');setRows(Array.isArray(d)?d:[])}
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{await api('/api/admin/metafields',{method:'POST',body:JSON.stringify(form)});setForm({namespace:'custom',key:'',name:'',description:'',type:'single_line_text_field',ownerType:'PRODUCT',isList:false});setOpen(false);setNotice('Custom field created.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to create custom field')}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Delete this custom field definition? Existing values may become unusable.'))return;setError('');try{await api(`/api/admin/metafields?id=${encodeURIComponent(id)}`,{method:'DELETE'});setRows(rows.filter(x=>x.id!==id));setNotice('Custom field deleted.')}catch(e){setError(e instanceof Error?e.message:'Unable to delete custom field')}}
 return <div className="catalogPage"><div className="sectionHead catalogHead"><div><span className="muted">SETTINGS · CUSTOM DATA</span><h1 className="h2">Custom data</h1><p className="muted">Define structured fields for products and other commerce entities.</p></div><button className="btn" type="button" onClick={()=>{setOpen(v=>!v);setError('');setNotice('')}}><Plus size={16}/>{open?'Cancel':'Add definition'}</button></div>{error&&<div className="alert danger">{error}</div>}{notice&&<div className="alert">{notice}</div>}{open&&<form onSubmit={create} className="card adminPanel grid fourFields" style={{marginBottom:16}}><input className="input" required placeholder="Namespace" value={form.namespace} onChange={e=>setForm({...form,namespace:e.target.value})}/><input className="input" required placeholder="Key" pattern="[A-Za-z0-9_\\-]+" value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/><input className="input" required placeholder="Display name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="input" value={form.ownerType} onChange={e=>setForm({...form,ownerType:e.target.value})}><option>PRODUCT</option><option>COLLECTION</option><option>ORDER</option><option>CUSTOMER</option></select><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="single_line_text_field">Single-line text</option><option value="multi_line_text_field">Multi-line text</option><option value="number_integer">Integer</option><option value="number_decimal">Decimal</option><option value="boolean">Boolean</option><option value="date">Date</option><option value="json">JSON</option></select><input className="input" placeholder="Description (optional)" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="inline"><input type="checkbox" checked={form.isList} onChange={e=>setForm({...form,isList:e.target.checked})}/> List field</label><button className="btn" disabled={busy}>{busy?'Creating…':'Create definition'}</button></form>}<div className="card productTableCard"><div className="tableWrap"><table className="table productTable"><thead><tr><th>Field</th><th>Namespace / key</th><th>Type</th><th>Owner</th><th>List</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><div className="inline"><Code2 size={16}/><div><strong>{r.name}</strong><div className="muted">{r.description||'No description'}</div></div></div></td><td><code>{r.namespace}.{r.key}</code></td><td>{r.type}</td><td>{r.ownerType}</td><td>{r.isList?'Yes':'No'}</td><td><button type="button" className="iconBtn dangerIcon" onClick={()=>remove(r.id)} title="Delete"><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty"><Code2 size={28}/><h3>No custom data definitions</h3><p className="muted">Create your first structured field.</p></div>}</div></div>
}
