'use client'
import {useState} from 'react'
import {GripVertical,Plus,Trash2,ChevronDown,Save} from 'lucide-react'
export default function NavigationEditor({initial,categories}:{initial:any[];categories:any[]}){
 const [items,setItems]=useState(initial),[saving,setSaving]=useState(false),[msg,setMsg]=useState('')
 const addCustom=()=>setItems(p=>[...p,{id:`item-${Date.now()}`,label:'New link',type:'custom',url:'#',parentId:null,children:[]}])
 const addCategory=()=>{const c=categories.find(x=>!items.some((i:any)=>i.resourceId===x.id));if(c)setItems(p=>[...p,{id:`cat-${c.id}`,label:c.name,type:'category',url:`/shop?category=${c.slug}`,resourceId:c.id,parentId:null,children:[]}])}
 const save=async()=>{setSaving(true);try{const theme=await (await fetch('/api/admin/theme')).json();const r=await fetch('/api/admin/theme',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...theme,navigation:items})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save');setMsg('Saved')}catch(e){setMsg(e instanceof Error?e.message:'Unable to save')}finally{setSaving(false)}}
 const move=(i:number,d:number)=>setItems(p=>{const n=[...p],j=i+d;if(j<0||j>=n.length)return p;[n[i],n[j]]=[n[j],n[i]];return n})
 return <div><div className="sectionHead"><div><span className="muted">ONLINE STORE / CONTENT</span><h1 className="h2">Navigation</h1><p className="muted">Build a Shopify-style menu. Categories and custom links can be nested into dropdowns.</p></div><div className="inline"><button className="btn secondary" onClick={addCategory}><Plus size={15}/> Category</button><button className="btn secondary" onClick={addCustom}><Plus size={15}/> Custom link</button><button className="btn" onClick={save} disabled={saving}><Save size={15}/> {saving?'Saving…':'Save'}</button></div></div>{msg&&<div className="alert">{msg}</div>}<div className="navEditorLayout"><section className="card adminPanel"><div className="sectionHead small"><h3>Main menu</h3><span className="muted">Drag order is preserved on save</span></div><div className="navBuilder">{items.map((item:any,i:number)=><div className="navEditRow" key={item.id}><button className="iconBtn"><GripVertical size={16}/></button><input className="input" value={item.label} onChange={e=>setItems(p=>p.map((x:any,ix:number)=>ix===i?{...x,label:e.target.value}:x))}/><select className="input navParent" value={item.parentId||''} onChange={e=>setItems(p=>p.map((x:any,ix:number)=>ix===i?{...x,parentId:e.target.value||null}:x))}><option value="">Top level</option>{items.filter((x:any)=>x.id!==item.id&&!x.parentId).map((x:any)=><option key={x.id} value={x.id}>↳ {x.label}</option>)}</select><select className="input navType" value={item.type} onChange={e=>setItems(p=>p.map((x:any,ix:number)=>ix===i?{...x,type:e.target.value}:x))}><option value="custom">Custom link</option><option value="category">Category</option><option value="collection">Collection</option></select><input className="input" value={item.url||''} onChange={e=>setItems(p=>p.map((x:any,ix:number)=>ix===i?{...x,url:e.target.value}:x))}/><button className="iconBtn" onClick={()=>move(i,-1)}>↑</button><button className="iconBtn" onClick={()=>move(i,1)}>↓</button><button className="iconBtn" onClick={()=>setItems(p=>p.filter((_,ix)=>ix!==i))}><Trash2 size={15}/></button></div>)}</div><div className="navTip"><strong>Dropdowns</strong><span>Use the hierarchy above; categories can later be nested under a top-level item. The storefront supports two nested levels and mobile accordion behavior.</span></div></section><aside className="card adminPanel"><div className="sectionHead small"><h3>Preview</h3></div><div className="navPreview"><div className="navPreviewHeader">YOUR BRAND</div>{items.map((i:any)=><div className="navPreviewItem" key={i.id}>{i.label}<ChevronDown size={14}/></div>)}</div></aside></div></div>
}
