'use client'
import { useMemo, useState } from 'react'
import { ChevronDown, ChevronRight, GripVertical, Plus, Save, Trash2, Eye, ExternalLink } from 'lucide-react'

type Item={id:string;label:string;url?:string|null;type?:string;parentId?:string|null;children?:Item[];resourceId?:string|null}
export default function NavigationEditorPro({initial,categories,collections}:{initial:Item[];categories:any[];collections:any[]}){
 const [items,setItems]=useState<Item[]>(initial||[]),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[preview,setPreview]=useState(true)
 const top=useMemo(()=>items.filter(x=>!x.parentId),[items]); const children=(id:string)=>items.filter(x=>x.parentId===id)
 const add=(type='custom')=>setItems(p=>[...p,{id:`nav-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,label:type==='category'?'New category':type==='collection'?'New collection':'New link',type,url:type==='category'?'/shop':type==='collection'?'/collections':'#',parentId:null,children:[]}])
 const patch=(id:string,data:Partial<Item>)=>setItems(p=>p.map(x=>x.id===id?{...x,...data}:x))
 const move=(id:string,d:number)=>setItems(p=>{const roots=p.filter(x=>!x.parentId),i=roots.findIndex(x=>x.id===id),j=i+d;if(i<0||j<0||j>=roots.length)return p;[roots[i],roots[j]]=[roots[j],roots[i]];const map=new Map(roots.map(x=>[x.id,x]));return [...Array.from(map.values()),...p.filter(x=>x.parentId)]})
 const save=async()=>{setSaving(true);setMsg('');try{const theme=await (await fetch('/api/admin/theme')).json();const r=await fetch('/api/admin/theme',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...theme,navigation:items})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save');setMsg('Navigation saved')}catch(e){setMsg(e instanceof Error?e.message:'Unable to save')}finally{setSaving(false)}}
 const row=(x:Item,level=0)=><div key={x.id}><div className="navProRow" style={{marginLeft:level*26}}><button className="iconBtn" title="Drag"><GripVertical size={15}/></button><input className="input" value={x.label} onChange={e=>patch(x.id,{label:e.target.value})}/><select className="input navProType" value={x.type||'custom'} onChange={e=>patch(x.id,{type:e.target.value})}><option value="custom">Link</option><option value="category">Category</option><option value="collection">Collection</option></select><input className="input navProUrl" value={x.url||''} onChange={e=>patch(x.id,{url:e.target.value})}/><button className="iconBtn" title="Move up" onClick={()=>move(x.id,-1)}>↑</button><button className="iconBtn" title="Move down" onClick={()=>move(x.id,1)}>↓</button><button className="iconBtn" title="Remove" onClick={()=>setItems(p=>p.filter(i=>i.id!==x.id&&i.parentId!==x.id))}><Trash2 size={15}/></button></div>{children(x.id).map(c=>row(c,level+1))}</div>
 return <div className="navProPage"><div className="sectionHead"><div><span className="muted">ONLINE STORE</span><h1 className="h2">Navigation</h1><p className="muted">Build menus, dropdowns and nested links with a live storefront preview.</p></div><div className="inline"><button className="btn secondary" onClick={()=>setPreview(v=>!v)}>{preview?<Eye size={15}/>:<ExternalLink size={15}/>} {preview?'Hide preview':'Show preview'}</button><button className="btn" disabled={saving} onClick={save}><Save size={15}/>{saving?'Saving…':'Save menu'}</button></div></div>{msg&&<div className="alert">{msg}</div>}<div className="navProLayout"><section className="card navProBuilder"><div className="navProToolbar"><div><strong>Main menu</strong><div className="muted">{top.length} top-level items · drag/reorder ready</div></div><div className="inline"><button className="btn secondary" onClick={()=>add('category')}><Plus size={14}/> Category</button><button className="btn secondary" onClick={()=>add('collection')}><Plus size={14}/> Collection</button><button className="btn secondary" onClick={()=>add('custom')}><Plus size={14}/> Link</button></div></div><div className="navProRows">{top.map(x=>row(x))}</div><div className="navProHint"><strong>Tip</strong><span>Use the type and URL fields to connect pages, collections or categories. Nesting is preserved when you save.</span></div></section>{preview&&<aside className="card navProPreview"><div className="navProPreviewHead"><strong>Storefront preview</strong><span className="muted">Desktop</span></div><div className="navPreviewPro"><div className="navBrand">YOUR BRAND</div><div className="navMenu">{top.map(x=><div className="navMenuItem" key={x.id}>{x.label}{children(x.id).length>0&&<ChevronDown size={14}/>} </div>)}</div>{top.filter(x=>children(x.id).length).slice(0,2).map(x=><div className="navDropdown" key={x.id}><strong>{x.label}</strong>{children(x.id).map(c=><div key={c.id}><ChevronRight size={13}/>{c.label}</div>)}</div>)}</div></aside>}</div></div>
}
