'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, PackageCheck, Mail, Phone, MapPin, Save, Plus, Copy, Check } from 'lucide-react'
import { money } from '@/lib/config'

async function api(path: string, init?: RequestInit) {
  const r = await fetch(path, { ...init, headers: { 'content-type': 'application/json', ...(init?.headers || {}) } })
  const d = await r.json().catch(() => ({}))
  if (!r.ok) throw new Error(d.error || 'Request failed')
  return d
}

function addressText(raw: string | null | undefined) {
  if (!raw) return '—'
  try { const a = JSON.parse(raw); return [`${a.firstName || ''} ${a.lastName || ''}`.trim(),a.line1,a.line2,[a.city,a.region,a.postalCode].filter(Boolean).join(', '),a.country,a.phone].filter(Boolean).join('\n') } catch { return raw }
}

export default function OrderDetailAdmin({ initial }: { initial: any }) {
  const [o, setO] = useState(initial); const [status, setStatus] = useState(o.status); const [paymentStatus, setPaymentStatus] = useState(o.paymentStatus); const [tracking, setTracking] = useState(o.trackingNumber || ''); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false); const [addingNote, setAddingNote] = useState(false); const [copied, setCopied] = useState(false); const [msg, setMsg] = useState('')
  const itemCount = useMemo(() => (o.items || []).reduce((a: number, x: any) => a + x.quantity, 0), [o.items])
  async function save(){setSaving(true);setMsg('');try{const d=await api('/api/admin/orders',{method:'PATCH',body:JSON.stringify({id:o.id,status,paymentStatus,trackingNumber:tracking})});setO((c:any)=>({...c,...(d.order||{}),status,paymentStatus,trackingNumber:tracking}));setMsg('Order updated successfully.')}catch(e){setMsg(e instanceof Error?e.message:'Unable to update order')}finally{setSaving(false)}}
  async function addNote(){const value=note.trim();if(!value)return;setAddingNote(true);setMsg('');try{const d=await api('/api/admin/orders',{method:'PATCH',body:JSON.stringify({id:o.id,addNote:value})});setO((c:any)=>({...c,notesHistory:[d.note,...(c.notesHistory||[])]}));setNote('');setMsg('Internal note added.')}catch(e){setMsg(e instanceof Error?e.message:'Unable to add note')}finally{setAddingNote(false)}}
  async function copyOrderNumber(){try{await navigator.clipboard.writeText(String(o.orderNumber));setCopied(true);window.setTimeout(()=>setCopied(false),1500)}catch{}}
  return <div><div className="sectionHead"><div><Link className="textLink" href="/admin/orders"><ArrowLeft size={15}/> Back to orders</Link><span className="muted tiny" style={{display:'block',marginTop:12}}>ORDER</span><div className="inline" style={{gap:8}}><h1 className="h2">#{o.orderNumber}</h1><button className="btn ghost smallBtn" onClick={copyOrderNumber}>{copied?<Check size={14}/>:<Copy size={14}/>}</button></div><p className="muted">Placed {new Date(o.createdAt).toLocaleString()}</p></div><div className="inline"><Link className="btn secondary" href={`/admin/orders/${o.id}/invoice`}>Invoice / Print</Link><span className="pill">{o.paymentStatus}</span><span className="pill">{o.fulfillmentStatus}</span></div></div>
    {msg&&<div className="alert">{msg}</div>}
    <div className="orderDetailGrid"><main className="orderDetailMain"><section className="card adminPanel"><div className="sectionHead small"><h3>Items</h3><span className="muted">{itemCount} items</span></div>{(o.items||[]).map((x:any)=><div className="orderItemRow" key={x.id}><div className="orderItemImage">{x.product?.images?.[0]?.url?<img src={x.product.images[0].url} alt=""/>:<PackageCheck size={18}/>}</div><div><strong>{x.name}</strong><div className="muted">{x.sku}{x.variant?.name?` • ${x.variant.name}`:''}</div></div><span>× {x.quantity}</span><strong>{money(x.totalPrice,o.currency)}</strong></div>)}<div className="summaryBox"><div><span>Subtotal</span><strong>{money(o.subtotal,o.currency)}</strong></div><div><span>Discount</span><strong>- {money(o.discountTotal,o.currency)}</strong></div><div><span>Shipping</span><strong>{money(o.shippingTotal,o.currency)}</strong></div><div><span>Tax</span><strong>{money(o.taxTotal,o.currency)}</strong></div><div className="total"><span>Total</span><strong>{money(o.grandTotal,o.currency)}</strong></div></div></section>
      <section className="card adminPanel"><div className="sectionHead small"><h3>Internal notes</h3></div><div className="inline" style={{alignItems:'stretch'}}><textarea className="input" rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a private note for staff…"/><button className="btn" onClick={addNote} disabled={addingNote||!note.trim()}><Plus size={15}/>{addingNote?'Adding…':'Add note'}</button></div><div className="timeline" style={{marginTop:18}}>{(o.notesHistory||[]).map((n:any)=><div className="timelineItem" key={n.id}><div className="dot"/><div><strong>{n.user?.name||'Staff'}</strong><p>{n.body}</p><small className="muted">{new Date(n.createdAt).toLocaleString()}</small></div></div>)}{!o.notesHistory?.length&&<p className="muted">No internal notes yet.</p>}</div></section>
      <section className="card adminPanel"><div className="sectionHead small"><h3>Order timeline</h3></div><div className="timeline">{(o.events||[]).map((e:any)=><div className="timelineItem" key={e.id}><div className="dot"/><div><strong>{e.status}</strong><p className="muted">{e.message||'Order updated'}</p><small className="muted">{new Date(e.createdAt).toLocaleString()}</small></div></div>)}{!o.events?.length&&<p className="muted">No status events yet.</p>}</div></section></main>
      <aside className="orderDetailRail"><section className="card adminPanel"><div className="sectionHead small"><h3>Order controls</h3></div><label className="fieldLabel">Fulfillment status<select className="input" value={status} onChange={e=>setStatus(e.target.value)}>{['PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','REFUNDED'].map(x=><option key={x}>{x}</option>)}</select></label><label className="fieldLabel">Payment status<select className="input" value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)}>{['UNPAID','PENDING','PAID','FAILED','PARTIALLY_REFUNDED','REFUNDED'].map(x=><option key={x}>{x}</option>)}</select></label><label className="fieldLabel">Tracking number<input className="input" value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="Enter tracking number"/></label><button className="btn" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save changes'}</button></section>
        <section className="card adminPanel"><div className="sectionHead small"><h3>Customer</h3></div><strong>{o.user?.name||o.email}</strong><p className="muted"><Mail size={13}/> {o.email}</p>{o.phone&&<p className="muted"><Phone size={13}/> {o.phone}</p>}{o.user?.id&&<Link className="textLink" href={`/admin/customers/${o.user.id}`}>Open customer</Link>}</section>
        <section className="card adminPanel"><div className="sectionHead small"><h3>Shipping address</h3></div><div className="muted" style={{whiteSpace:'pre-wrap'}}><MapPin size={13}/> {addressText(o.shippingAddressJson)}</div>{o.shippingMethod&&<p className="muted">Method: {o.shippingMethod}</p>}{o.trackingNumber&&<p className="muted">Tracking: <strong>{o.trackingNumber}</strong></p>}</section>
        <section className="card adminPanel"><div className="sectionHead small"><h3>Billing address</h3></div><div className="muted" style={{whiteSpace:'pre-wrap'}}>{addressText(o.billingAddressJson)}</div></section>
        <section className="card adminPanel"><div className="sectionHead small"><h3>Payment</h3></div><div className="summaryLine"><span>Method</span><strong>{o.paymentMethod}</strong></div><div className="summaryLine"><span>Status</span><strong>{o.paymentStatus}</strong></div>{(o.paymentTransactions||[]).map((t:any)=><div key={t.id} className="summaryLine"><span>{t.provider}{t.externalId?` • ${t.externalId}`:''}</span><span>{t.status} · {money(t.amount,t.currency)}</span></div>)}</section>
        <section className="card adminPanel"><div className="sectionHead small"><h3>Order information</h3></div><div className="summaryLine"><span>Currency</span><strong>{o.currency}</strong></div><div className="summaryLine"><span>Coupon</span><strong>{o.couponCode||'—'}</strong></div><div className="summaryLine"><span>Created</span><strong>{new Date(o.createdAt).toLocaleDateString()}</strong></div><div className="summaryLine"><span>Updated</span><strong>{new Date(o.updatedAt).toLocaleString()}</strong></div></section>
      </aside></div></div>
}
