'use client'
import {useMemo,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,ChevronDown,GripVertical,Image as ImageIcon,Plus,Trash2,Search,Save,Eye,MoreHorizontal} from 'lucide-react'

async function request(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{'content-type':'application/json',...(init?.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data}

type ProductImage={id?:string,url:string,alt?:string|null}
type Variant={id?:string,name:string,sku:string,barcode?:string|null,optionJson:string,price?:number|null,compareAtPrice?:number|null,quantity?:number,lowStockThreshold?:number,location?:string,weight?:number|null,weightUnit?:string|null}
type Product={id?:string,name:string,slug:string,description?:string|null,shortDescription?:string|null,brand?:string|null,vendor?:string|null,productType?:string|null,basePrice:number,compareAtPrice?:number|null,costPrice?:number|null,sku:string,barcode?:string|null,status:string,featured:boolean,seoTitle?:string|null,seoDescription?:string|null,seoImageUrl?:string|null,weight?:number|null,weightUnit?:string|null,requiresShipping:boolean,taxable:boolean,trackInventory:boolean,continueSellingWhenOutOfStock:boolean,giftCard:boolean,productTemplate?:string|null,categoryId?:string|null,publishedAt?:string|null,images:ProductImage[],variants:Variant[],inventory:any[],tags:any[],category?:any|null,metafields?:any[],quantity?:number,lowStockThreshold?:number,location?:string}

const tabs=['General','Inventory','Shipping','Variants','Metafields','Search & SEO'] as const
export default function ProductEditor({initial,creating,categories,definitions}:{initial:Product,creating:boolean,categories:any[],definitions:any[]}){
  const [tab,setTab]=useState<typeof tabs[number]>('General')
  const [product,setProduct]=useState<Product>(initial)
  const [newTag,setNewTag]=useState('')
  const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(''); const [err,setErr]=useState('')
  const [optionNames,setOptionNames]=useState<string[]>([''])
  const [optionValues,setOptionValues]=useState<string[][]>([['']])
  const imageCount=product.images?.length||0
  const hasVariants=product.variants?.length>0
  const available=useMemo(()=>product.quantity!==undefined?product.quantity:(product.inventory?.reduce((s:any,x:any)=>s+(x.quantity-x.reserved),0)||0),[product.quantity,product.inventory])
  const update=(patch:Partial<Product>)=>setProduct(p=>({...p,...patch}))
  const save=async()=>{
    setBusy(true);setMsg('');setErr('')
    try{
      const payload={...product,basePrice:Math.round(Number(product.basePrice)||0),compareAtPrice:product.compareAtPrice==null?null:Math.round(Number(product.compareAtPrice)),costPrice:product.costPrice==null?null:Math.round(Number(product.costPrice)),tags:(product.tags||[]).map((x:any)=>typeof x==='string'?x:x.value)}
      const data=creating?await request('/api/admin/products',{method:'POST',body:JSON.stringify(payload)}):await request(`/api/admin/products/${product.id}`,{method:'PATCH',body:JSON.stringify(payload)})
      const saved=data.product; if(creating) window.location.href=`/admin/products/${saved.id}`; else {setMsg('Saved');setProduct(p=>({...p,id:saved.id}))}
    }catch(e){setErr(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}
  }
  const addImage=()=>update({images:[...(product.images||[]),{url:'',alt:''}]})
  const updateImage=(i:number,patch:Partial<ProductImage>)=>update({images:product.images.map((x,idx)=>idx===i?{...x,...patch}:x)})
  const removeImage=(i:number)=>update({images:product.images.filter((_,idx)=>idx!==i)})
  const addVariant=()=>update({variants:[...(product.variants||[]),{name:'New variant',sku:`${product.sku}-${(product.variants?.length||0)+1}`,optionJson:'{}',price:product.basePrice,quantity:0,lowStockThreshold:5,location:'Main'}]})
  const removeVariant=(i:number)=>update({variants:product.variants.filter((_,idx)=>idx!==i)})
  const addTag=()=>{const t=newTag.trim();if(!t)return;update({tags:[...(product.tags||[]),{value:t}]});setNewTag('')}
  const addOption=()=>{if(optionNames.length>=3)return;setOptionNames(x=>[...x,'']);setOptionValues(x=>[...x,['']])}
  return <div className="productEditor">
    <div className="editorTopbar">
      <div className="editorTopLeft"><Link href="/admin/products" className="iconBtn" aria-label="Back"><ArrowLeft size={18}/></Link><div><div className="muted tiny">PRODUCTS</div><h1 className="editorTitle">{creating?'Add product':product.name||'Untitled product'}</h1></div></div>
      <div className="editorTopActions"><Link href={creating?'/admin/products':`/product/${product.slug}`} target="_blank" className="btn secondary"><Eye size={16}/> Preview</Link><button className="btn" onClick={save} disabled={busy}>{busy?<span>Saving…</span>:<><Save size={16}/> Save</>}</button><button className="iconBtn"><MoreHorizontal size={18}/></button></div>
    </div>
    {(err||msg)&&<div className={err?'alert danger':'alert'} style={{margin:'0 24px 14px'}}>{err||msg}</div>}
    <div className="editorTabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
    <div className="editorBody">
      <main className="editorMain">
        {tab==='General'&&<>
          <EditorCard title="Title & description" subtitle="Create the storefront-facing product listing."><label className="fieldLabel">Title<input className="input" value={product.name} onChange={e=>update({name:e.target.value})}/></label><label className="fieldLabel">Description<textarea className="textarea richArea" rows={10} value={product.description||''} onChange={e=>update({description:e.target.value})}/><span className="fieldHelp">This editor stores HTML/plain text safely; a rich text editor can be swapped in later without changing the data model.</span></label></EditorCard>
          <EditorCard title="Media" subtitle={`${imageCount} ${imageCount===1?'image':'images'} • drag order is preserved`}><div className="mediaEditorGrid">{product.images.map((im,i)=><div className="mediaEditItem" key={im.id||i}><div className="dragHandle"><GripVertical size={15}/></div>{im.url?<img src={im.url} alt={im.alt||''}/>:<div className="mediaPlaceholder"><ImageIcon size={24}/><span>Add URL</span></div>}<div className="mediaEditControls"><input className="input" placeholder="Image URL" value={im.url} onChange={e=>updateImage(i,{url:e.target.value})}/><input className="input" placeholder="Alt text" value={im.alt||''} onChange={e=>updateImage(i,{alt:e.target.value})}/><button className="textButton dangerText" onClick={()=>removeImage(i)}><Trash2 size={14}/> Remove</button></div></div>)}<button className="mediaAdd" onClick={addImage}><Plus size={18}/><span>Add media</span></button></div></EditorCard>
          <EditorCard title="Organization" subtitle="Control how the product is categorized and discovered."><div className="twoColFields"><Field label="Vendor / brand"><input className="input" value={product.vendor||product.brand||''} onChange={e=>update({vendor:e.target.value,brand:e.target.value})}/></Field><Field label="Product type"><input className="input" value={product.productType||''} onChange={e=>update({productType:e.target.value})}/></Field><Field label="Category"><select className="input" value={product.categoryId||''} onChange={e=>update({categoryId:e.target.value||null})}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.parentId?'↳ ':''}{c.name}</option>)}</select></Field><Field label="Status"><select className="input" value={product.status} onChange={e=>update({status:e.target.value,publishedAt:e.target.value==='ACTIVE'?(new Date().toISOString()):null})}><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select></Field></div><label className="fieldLabel">Tags<div className="tagRow">{(product.tags||[]).map((t:any,i:number)=><span className="tagChip" key={i}>{typeof t==='string'?t:t.value}<button onClick={()=>update({tags:(product.tags||[]).filter((_,idx)=>idx!==i)})}>×</button></span>)}<div className="tagAdd"><input className="input" value={newTag} placeholder="Add tag" onChange={e=>setNewTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTag()}}}/><button className="btn secondary smallBtn" onClick={addTag}>Add</button></div></div></label></EditorCard>
          <EditorCard title="Pricing" subtitle="Customer price, compare-at price, cost and margin controls."><div className="threeColFields"><MoneyField label="Price" value={product.basePrice ?? undefined} onChange={v=>update({basePrice:v})}/><MoneyField label="Compare-at price" value={product.compareAtPrice ?? undefined} onChange={v=>update({compareAtPrice:v})}/><MoneyField label="Cost per item" value={product.costPrice ?? undefined} onChange={v=>update({costPrice:v})}/></div><div className="pricingPreview"><span>Margin</span><strong>{product.costPrice&&product.basePrice?`${Math.max(0,Math.round((1-product.costPrice/product.basePrice)*100))}%`: '—'}</strong></div></EditorCard>
        </>}
        {tab==='Inventory'&&<>
          <EditorCard title="Inventory" subtitle="Track availability, SKU and barcode without touching code."><div className="threeColFields"><Field label="SKU"><input className="input" value={product.sku} onChange={e=>update({sku:e.target.value})}/></Field><Field label="Barcode"><input className="input" value={product.barcode||''} onChange={e=>update({barcode:e.target.value})}/></Field><Field label="Available"><input className="input" type="number" value={available} onChange={e=>update({quantity:Number(e.target.value)})}/></Field></div><div className="checkGrid"><Check checked={product.trackInventory} onChange={v=>update({trackInventory:v})} title="Track quantity" text="Automatically prevent overselling unless the product allows it."/><Check checked={product.continueSellingWhenOutOfStock} onChange={v=>update({continueSellingWhenOutOfStock:v})} title="Continue selling when out of stock" text="Allow checkout when available inventory reaches zero."/></div></EditorCard>
          <EditorCard title="Inventory locations" subtitle="Ready for multiple locations and transfers."><div className="tableWrap"><table className="table"><thead><tr><th>Location</th><th>Available</th><th>Reserved</th><th>Low stock at</th></tr></thead><tbody>{(product.inventory||[]).map((x:any,i:number)=><tr key={x.id||i}><td><strong>{x.location||'Main'}</strong></td><td>{x.quantity}</td><td>{x.reserved}</td><td><input className="input compact" type="number" value={x.lowStockThreshold} onChange={e=>{const next=[...(product.inventory||[])];next[i]={...next[i],lowStockThreshold:Number(e.target.value)};update({inventory:next})}}/></td></tr>)}</tbody></table></div></EditorCard>
        </>}
        {tab==='Shipping'&&<EditorCard title="Shipping" subtitle="Control fulfillment, weights and tax behavior."><div className="checkGrid"><Check checked={product.requiresShipping} onChange={v=>update({requiresShipping:v})} title="This is a physical product" text="Collect shipping details at checkout."/><Check checked={product.taxable} onChange={v=>update({taxable:v})} title="Charge tax on this product" text="Use store tax rules when calculating totals."/><Check checked={product.giftCard} onChange={v=>update({giftCard:v})} title="Gift card" text="Reserved for gift-card product types."/></div><div className="threeColFields" style={{marginTop:16}}><Field label="Weight"><input className="input" type="number" step="0.01" value={product.weight??''} onChange={e=>update({weight:e.target.value===''?null:Number(e.target.value)})}/></Field><Field label="Weight unit"><select className="input" value={product.weightUnit||'kg'} onChange={e=>update({weightUnit:e.target.value})}><option>kg</option><option>g</option><option>lb</option><option>oz</option></select></Field><Field label="Template"><select className="input" value={product.productTemplate||'product'} onChange={e=>update({productTemplate:e.target.value})}><option value="product">Default product</option><option value="product.featured">Featured product</option><option value="product.minimal">Minimal product</option></select></Field></div></EditorCard>}
        {tab==='Variants'&&<>
          <EditorCard title="Options" subtitle="Define up to three option dimensions and generate variants later."><div className="optionList">{optionNames.map((n,i)=><div className="optionRow" key={i}><input className="input" placeholder={`Option ${i+1} name (e.g. Size)`} value={n} onChange={e=>{const a=[...optionNames];a[i]=e.target.value;setOptionNames(a)}}/><input className="input" placeholder="Values (comma separated)" value={(optionValues[i]||[]).join(', ')} onChange={e=>{const a=[...optionValues];a[i]=e.target.value.split(',').map(v=>v.trim()).filter(Boolean);setOptionValues(a)}}/>{optionNames.length>1&&<button className="iconBtn" onClick={()=>{setOptionNames(optionNames.filter((_,x)=>x!==i));setOptionValues(optionValues.filter((_,x)=>x!==i))}}><Trash2 size={16}/></button>}</div>)}<button className="btn secondary" onClick={addOption} disabled={optionNames.length>=3}><Plus size={16}/> Add option</button></div></EditorCard>
          <EditorCard title="Variants" subtitle={`${hasVariants?product.variants.length:0} variants`}><div className="variantHead"><span>Variant</span><span>SKU</span><span>Price</span><span>Stock</span><span></span></div>{(product.variants||[]).map((v,i)=><div className="variantRow" key={v.id||i}><input className="input" value={v.name} onChange={e=>{const a=[...product.variants];a[i]={...a[i],name:e.target.value};update({variants:a})}}/><input className="input" value={v.sku} onChange={e=>{const a=[...product.variants];a[i]={...a[i],sku:e.target.value};update({variants:a})}}/><input className="input" type="number" step="0.01" value={(v.price||0)/100} onChange={e=>{const a=[...product.variants];a[i]={...a[i],price:Math.round(Number(e.target.value||0)*100)};update({variants:a})}}/><input className="input" type="number" value={v.quantity||0} onChange={e=>{const a=[...product.variants];a[i]={...a[i],quantity:Number(e.target.value)};update({variants:a})}}/><button className="iconBtn" onClick={()=>removeVariant(i)}><Trash2 size={16}/></button></div>)}<button className="btn secondary" onClick={addVariant}><Plus size={16}/> Add variant</button></EditorCard>
        </>}
        {tab==='Metafields'&&<EditorCard title="Metafields" subtitle="Structured custom data for advanced merchandising, SEO and operations.">{definitions.length===0?<div className="emptyInline"><strong>No definitions yet</strong><span className="muted">Create reusable definitions from Settings → Custom data, then they appear here.</span><Link className="btn secondary smallBtn" href="/admin/settings#custom-data">Open custom data</Link></div>:<div className="metafieldEditor">{definitions.map((d:any)=>{const current=(product.metafields||[]).find((m:any)=>m.definitionId===d.id)?.value||'';return <label className="fieldLabel" key={d.id}>{d.name}<span className="fieldHelp">{d.namespace}.{d.key} · {d.type}</span><input className="input" value={current} onChange={e=>{const next=[...(product.metafields||[])].filter((m:any)=>m.definitionId!==d.id);next.push({definitionId:d.id,value:e.target.value,definition:d});update({metafields:next})}}/></label>})}</div>}</EditorCard>}
        {tab==='Search & SEO'&&<><EditorCard title="Search engine listing" subtitle="Control what search engines see for this product."><Field label="Page title"><input className="input" value={product.seoTitle||product.name} onChange={e=>update({seoTitle:e.target.value})}/></Field><Field label="Meta description"><textarea className="textarea" rows={5} value={product.seoDescription||product.shortDescription||product.description||''} onChange={e=>update({seoDescription:e.target.value})}/></Field><Field label="Search image URL"><input className="input" value={product.seoImageUrl||''} onChange={e=>update({seoImageUrl:e.target.value})}/></Field></EditorCard><EditorCard title="URL and handle"><Field label="Handle"><input className="input" value={product.slug} onChange={e=>update({slug:e.target.value})}/></Field><div className="urlPreview">/products/{product.slug}</div></EditorCard></>}
      </main>
      <aside className="editorRail">
        <EditorCard title="Publishing"><div className="statusRow"><span>Status</span><select className="input compact" value={product.status} onChange={e=>update({status:e.target.value})}><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select></div><div className="publishList"><label><input type="checkbox" checked={product.status==='ACTIVE'} onChange={e=>update({status:e.target.checked?'ACTIVE':'DRAFT'})}/> Online store</label><label><input type="checkbox" defaultChecked/> POS</label></div></EditorCard>
        <EditorCard title="Product insights"><div className="insight"><span>Inventory</span><strong>{available}</strong></div><div className="insight"><span>Variants</span><strong>{product.variants?.length||0}</strong></div><div className="insight"><span>Images</span><strong>{imageCount}</strong></div></EditorCard>
        <EditorCard title="Organization"><div className="miniLine"><span>Category</span><strong>{categories.find(c=>c.id===product.categoryId)?.name||'Uncategorized'}</strong></div><div className="miniLine"><span>Template</span><strong>{product.productTemplate||'product'}</strong></div></EditorCard>
        <EditorCard title="More actions"><button className="railAction"><Search size={15}/> View storefront search</button><button className="railAction"><Eye size={15}/> View product</button><button className="railAction dangerText"><Trash2 size={15}/> Archive product</button></EditorCard>
      </aside>
    </div>
  </div>
}

function EditorCard({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="editorCard"><div className="editorCardHead"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div><ChevronDown size={17}/></div><div className="editorCardBody">{children}</div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="fieldLabel">{label}{children}</label>}
function MoneyField({label,value,onChange}:{label:string;value?:number;onChange:(v:number|null)=>void}){return <Field label={label}><div className="moneyInput"><span>$</span><input className="input" type="number" min="0" step="0.01" value={value==null?'':(value/100).toFixed(2)} onChange={e=>onChange(e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></div></Field>}
function Check({checked,onChange,title,text}:{checked:boolean;onChange:(v:boolean)=>void;title:string;text:string}){return <label className="checkCard"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><div><strong>{title}</strong><span>{text}</span></div></label>}
