'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {Plus,Search,MoreHorizontal,Archive,CheckCircle2,AlertTriangle} from 'lucide-react'
import {money} from '@/lib/config'
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{'content-type':'application/json',...(init?.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data}
export default function ProductListAdmin({initial}:{initial:any[]}){
 const [rows,setRows]=useState(initial),[q,setQ]=useState(''),[filter,setFilter]=useState('ALL'),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function refresh(){setBusy(true);setError('');try{setRows(await api('/api/admin/products?q='+encodeURIComponent(q)))}catch(e){setError(e instanceof Error?e.message:'Unable to load products')}finally{setBusy(false)}}
 const filtered=rows.filter(p=>filter==='ALL'||p.status===filter)
 return <div><div className="sectionHead"><div><span className="muted">CATALOG</span><h1 className="h2">Products</h1><p className="muted">Manage titles, media, pricing, inventory, variants, SEO and publishing from one editor.</p></div><div className="inline"><Link className="btn" href="/admin/products/new"><Plus size={16}/> Add product</Link></div></div>{error&&<div className="alert danger">{error}</div>}<div className="productToolbar"><div className="productSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, SKUs, vendors…" onKeyDown={e=>{if(e.key==='Enter')refresh()}}/></div><div className="toolbarSelects"><select className="input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="DRAFT">Draft</option><option value="ARCHIVED">Archived</option></select><button className="btn secondary" onClick={refresh} disabled={busy}>{busy?'Searching…':'Search'}</button></div></div><div className="card productTableCard"><table className="table productTable"><thead><tr><th><input type="checkbox"/></th><th>Product</th><th>Status</th><th>Inventory</th><th>Category</th><th>Price</th><th>Updated</th><th></th></tr></thead><tbody>{filtered.map(p=>{const stock=(p.inventory||[]).reduce((a:any,x:any)=>a+x.quantity-x.reserved,0);return <tr key={p.id}><td><input type="checkbox"/></td><td><Link className="productListName" href={`/admin/products/${p.id}`}><div className="productThumb">{p.images?.[0]?.url?<img src={p.images[0].url} alt=""/>:<span>◎</span>}</div><div><strong>{p.name}</strong><div className="muted">{p.sku}</div></div></Link></td><td><span className={`statusPill ${String(p.status).toLowerCase()}`}>{p.status==='ACTIVE'?<CheckCircle2 size={13}/>:p.status==='DRAFT'?<AlertTriangle size={13}/>:<Archive size={13}/>} {p.status}</span></td><td><span className={stock<=5?'lowStock':''}>{stock}</span></td><td>{p.category?.name||'—'}</td><td>{money(p.basePrice)}</td><td>{new Date(p.updatedAt).toLocaleDateString()}</td><td><Link className="iconBtn" href={`/admin/products/${p.id}`}><MoreHorizontal size={17}/></Link></td></tr>})}</tbody></table>{filtered.length===0&&<div className="empty">No products match your filters.</div>}</div></div>
}
