'use client'

import { useMemo, useState } from 'react'
import { Check, Eye, RefreshCw, Star, X } from 'lucide-react'

type Review = { id:string; rating:number; title:string|null; body:string|null; approved:boolean; featured:boolean; createdAt:string; product:{id:string;name:string}; user:{id:string;name:string;email:string} }
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{'content-type':'application/json',...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
export default function ReviewsAdminShopify({initial}:{initial:Review[]}){
 const [rows,setRows]=useState(initial||[]),[tab,setTab]=useState('all'),[q,setQ]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState<string|null>(null)
 const shown=useMemo(()=>{const n=q.trim().toLowerCase();return rows.filter(r=>(tab==='all'||(tab==='pending'&&!r.approved)||(tab==='approved'&&r.approved)||(tab==='featured'&&r.featured))&&(!n||`${r.product.name} ${r.user.name} ${r.user.email} ${r.title||''} ${r.body||''}`.toLowerCase().includes(n)))},[rows,tab,q])
 async function refresh(){setError('');try{const d=await api('/api/admin/reviews');setRows(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:'Unable to load reviews')}}
 async function update(id:string,data:any,message:string){setBusy(id);setError('');setNotice('');try{await api('/api/admin/reviews',{method:'PATCH',body:JSON.stringify({id,...data})});await refresh();setNotice(message)}catch(e){setError(e instanceof Error?e.message:'Unable to update review')}finally{setBusy(null)}}
 return <div className="catalogPage reviewsAdminPage"><div className="sectionHead catalogHead"><div><span className="muted">TRUST & MODERATION</span><h1 className="h2">Reviews</h1><p className="muted">Moderate customer reviews before they appear on the storefront.</p></div><button className="btn secondary" onClick={refresh} disabled={busy!==null}><RefreshCw size={15}/> Refresh</button></div>{(error||notice)&&<div className={error?'alert danger':'alert'}>{error||notice}</div>}<div className="card orderViews">{[['all','All'],['pending','Pending'],['approved','Approved'],['featured','Featured']].map(([v,l])=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v as string)}>{l} <span>{v==='all'?rows.length:v==='pending'?rows.filter(r=>!r.approved).length:v==='approved'?rows.filter(r=>r.approved).length:rows.filter(r=>r.featured).length}</span></button>)}</div><div className="card catalogToolbar"><div className="productSearch"><Eye size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product, customer, review…"/>{q&&<button className="searchClear" onClick={()=>setQ('')} aria-label="Clear search"><X size={14}/></button>}</div><span className="muted">{shown.length} review{shown.length===1?'':'s'}</span></div><div className="card productTableCard"><div className="tableWrap"><table className="table productTable"><thead><tr><th>Review</th><th>Customer</th><th>Rating</th><th>Status</th><th>Featured</th><th></th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><strong>{r.product.name}</strong><div>{r.title||'Untitled review'}</div><div className="muted reviewSnippet">{r.body||'No written review'}</div><div className="muted">{new Date(r.createdAt).toLocaleString()}</div></td><td><strong>{r.user.name}</strong><div className="muted">{r.user.email}</div></td><td><span className="ratingStars">{'★'.repeat(Math.max(0,Math.min(5,r.rating)))}{'☆'.repeat(Math.max(0,5-r.rating))}</span></td><td><button className="iconTextBtn" disabled={busy===r.id} onClick={()=>update(r.id,{approved:!r.approved},r.approved?'Review moved to pending.':'Review approved.')}>{r.approved?<><Check size={16}/> Approved</>:<>Pending</>}</button></td><td><button className="iconTextBtn" disabled={busy===r.id} onClick={()=>update(r.id,{featured:!r.featured},r.featured?'Removed from featured.':'Added to featured.')}>{r.featured?<><Star size={16}/> Featured</>:<Star size={16}/>}</button></td><td><div className="inline"><a className="iconBtn" href={`/product/${(r.product as any).slug||''}`} target="_blank" rel="noreferrer" title="View product"><Eye size={15}/></a></div></td></tr>)}</tbody></table></div>{!shown.length&&<div className="empty"><Star size={28}/><h3>No reviews found</h3><p className="muted">Try another tab or search term.</p></div>}</div></div>
}
