'use client'

import { Copy, GripVertical, Plus, Trash2 } from 'lucide-react'

type Section = { id: string; type: string; enabled?: boolean; settings?: Record<string, any>; blocks?: any[] }

type Props = {
  section: Section
  products: any[]
  collections: any[]
  onUpdate: (patch: Record<string, any>) => void
  onUpdateBlocks: (blocks: any[]) => void
}

function Field({ label, value, onChange, placeholder }: { label: string; value: any; onChange: (value: string) => void; placeholder?: string }) {
  return <label className="themeInspectorField"><span>{label}</span><input value={value ?? ''} placeholder={placeholder} onChange={event => onChange(event.target.value)} /></label>
}
function TextArea({ label, value, onChange, placeholder }: { label: string; value: any; onChange: (value: string) => void; placeholder?: string }) {
  return <label className="themeInspectorField"><span>{label}</span><textarea value={value ?? ''} placeholder={placeholder} onChange={event => onChange(event.target.value)} /></label>
}
function Select({ label, value, options, onChange }: { label: string; value: any; options: Array<{value:string;label:string}> | string[]; onChange: (value: string) => void }) {
  const normalized = options.map(option => typeof option === 'string' ? { value: option, label: option } : option)
  return <label className="themeInspectorField"><span>{label}</span><select value={String(value ?? '')} onChange={event => onChange(event.target.value)}>{normalized.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) {
  return <label className="themeInspectorToggle"><span>{label}</span><button type="button" className={value ? 'on' : ''} aria-pressed={value} onClick={() => onChange(!value)}><i /></button></label>
}
function Range({ label, value, min, max, step = 1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void }) {
  return <label className="themeInspectorRange"><div><span>{label}</span><b>{value}</b></div><input type="range" value={Number.isFinite(value) ? value : min} min={min} max={max} step={step} onChange={event => onChange(Number(event.target.value))} /></label>
}
function SectionPanel({ title, children }: { title: string; children: React.ReactNode }) {
  return <details className="themeInspectorPanel" open><summary>{title}</summary><div>{children}</div></details>
}

function BlocksEditor({ section, type, onUpdateBlocks }: { section: Section; type: string; onUpdateBlocks: (blocks: any[]) => void }) {
  const blocks = Array.isArray(section.blocks) ? section.blocks : []
  const labels: Record<string,string> = { promo: 'Promo card', quote: 'Testimonial', column: 'Column', item: 'Item', question: 'FAQ item', slide: 'Slide', logo: 'Logo' }
  const label = labels[type] || 'Block'
  const add = () => onUpdateBlocks([...blocks, { id: `${type}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, type, settings: {} }])
  const update = (index: number, patch: Record<string,any>) => onUpdateBlocks(blocks.map((block,index2) => index===index2 ? {...block,settings:{...(block.settings||{}),...patch}} : block))
  const remove = (index: number) => onUpdateBlocks(blocks.filter((_,index2)=>index!==index2))
  return <div className="themeBlockList">{blocks.map((block,index)=><div className="themeBlock" key={block.id || index}><div className="themeBlockHeader"><GripVertical size={14}/><strong>{labels[block.type] || label} {index+1}</strong><button type="button" className="themeBlockDelete" onClick={()=>remove(index)} aria-label={`Delete ${label}`}><Trash2 size={14}/></button></div><div className="themeBlockFields">{type==='promo'&&<><Field label="Heading" value={block.settings?.heading} onChange={value=>update(index,{heading:value})}/><TextArea label="Text" value={block.settings?.text} onChange={value=>update(index,{text:value})}/><Field label="Image URL" value={block.settings?.imageUrl} onChange={value=>update(index,{imageUrl:value})}/><Field label="Link URL" value={block.settings?.url} onChange={value=>update(index,{url:value})}/></>}{type==='quote'&&<><TextArea label="Quote" value={block.settings?.quote} onChange={value=>update(index,{quote:value})}/><Field label="Author" value={block.settings?.author} onChange={value=>update(index,{author:value})}/><Field label="Role" value={block.settings?.role} onChange={value=>update(index,{role:value})}/><Select label="Rating" value={block.settings?.rating??5} options={['1','2','3','4','5']} onChange={value=>update(index,{rating:Number(value)})}/></>}{type==='column'&&<><Field label="Heading" value={block.settings?.heading} onChange={value=>update(index,{heading:value})}/><TextArea label="Text" value={block.settings?.text} onChange={value=>update(index,{text:value})}/><Field label="Icon / image URL" value={block.settings?.imageUrl} onChange={value=>update(index,{imageUrl:value})}/></>}{type==='question'&&<><Field label="Question" value={block.settings?.question||block.settings?.heading} onChange={value=>update(index,{question:value,heading:value})}/><TextArea label="Answer" value={block.settings?.answer||block.settings?.text} onChange={value=>update(index,{answer:value,text:value})}/></>}{type==='slide'&&<><Field label="Eyebrow" value={block.settings?.eyebrow} onChange={value=>update(index,{eyebrow:value})}/><Field label="Heading" value={block.settings?.heading} onChange={value=>update(index,{heading:value})}/><TextArea label="Text" value={block.settings?.text} onChange={value=>update(index,{text:value})}/><Field label="Image URL" value={block.settings?.imageUrl} onChange={value=>update(index,{imageUrl:value})}/><Field label="Button URL" value={block.settings?.buttonUrl} onChange={value=>update(index,{buttonUrl:value})}/></>}{type==='logo'&&<><Field label="Logo URL" value={block.settings?.imageUrl} onChange={value=>update(index,{imageUrl:value})}/><Field label="Alt text" value={block.settings?.alt} onChange={value=>update(index,{alt:value})}/><Field label="Link URL" value={block.settings?.url} onChange={value=>update(index,{url:value})}/></>}</div></div>)}<button type="button" className="themeAddBlock" onClick={add}><Plus size={14}/> Add {label}</button></div>
}

export default function ShopifyThemeInspector({ section, products, collections, onUpdate, onUpdateBlocks }: Props) {
  const s = section.settings || {}
  const set = (key: string, value: any) => onUpdate({ [key]: value })
  const addCommonLayout = () => <SectionPanel title="Layout & appearance"><div className="themeInspectorGrid"><Select label="Background" value={s.background || 'default'} options={['default','surface','secondary','dark','primary','gradient']} onChange={value=>set('background',value==='default'?'':value)}/><Select label="Text alignment" value={s.textAlign || 'left'} options={['left','center','right']} onChange={value=>set('textAlign',value)}/><Range label="Spacing" value={Number(s.spacing ?? 72)} min={0} max={160} onChange={value=>set('spacing',value)}/><Range label="Columns" value={Number(s.columns ?? 4)} min={2} max={6} onChange={value=>set('columns',value)}/></div></SectionPanel>
  return <div className="themeInspector">
    <SectionPanel title="General"><Toggle label="Section enabled" value={section.enabled !== false} onChange={value=>onUpdate({ enabled:value })}/><Field label="Section ID" value={section.id} onChange={()=>{}} /></SectionPanel>

    {section.type==='hero'&&<><SectionPanel title="Content"><Field label="Eyebrow" value={s.eyebrow} onChange={value=>set('eyebrow',value)}/><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Text" value={s.text} onChange={value=>set('text',value)}/><div className="themeInspectorGrid"><Field label="Button label" value={s.buttonLabel} onChange={value=>set('buttonLabel',value)}/><Field label="Button URL" value={s.buttonUrl} onChange={value=>set('buttonUrl',value)}/><Field label="Secondary label" value={s.secondaryLabel} onChange={value=>set('secondaryLabel',value)}/><Field label="Secondary URL" value={s.secondaryUrl} onChange={value=>set('secondaryUrl',value)}/></div></SectionPanel><SectionPanel title="Media"><Field label="Desktop image URL" value={s.desktopImageUrl || s.imageUrl} onChange={value=>set('desktopImageUrl',value)}/><Field label="Mobile image URL" value={s.mobileImageUrl} onChange={value=>set('mobileImageUrl',value)}/><Field label="Alt text" value={s.imageAlt} onChange={value=>set('imageAlt',value)}/><div className="themeInspectorGrid"><Select label="Image fit" value={s.imageFit || 'cover'} options={['cover','contain','fill']} onChange={value=>set('imageFit',value)}/><Select label="Overlay style" value={s.overlayStyle || 'bottom-gradient'} options={['none','solid','bottom-gradient','full-gradient']} onChange={value=>set('overlayStyle',value)}/><Range label="Overlay" value={Math.round(Number(s.overlay ?? .24)*100)} min={0} max={100} onChange={value=>set('overlay',value/100)}/><Field label="Overlay color" value={s.overlayColor || '#000000'} onChange={value=>set('overlayColor',value)}/></div><div className="themeInspectorGrid"><Range label="Focal X" value={Number(s.focalX ?? 50)} min={0} max={100} onChange={value=>set('focalX',value)}/><Range label="Focal Y" value={Number(s.focalY ?? 50)} min={0} max={100} onChange={value=>set('focalY',value)}/></div></SectionPanel><SectionPanel title="Position & size"><div className="themeInspectorGrid"><Select label="Content position" value={s.contentPosition || 'center-left'} options={['top-left','top-center','top-right','center-left','center','center-right','bottom-left','bottom-center','bottom-right']} onChange={value=>set('contentPosition',value)}/><Select label="Text alignment" value={s.textAlign || 'left'} options={['left','center','right']} onChange={value=>set('textAlign',value)}/><Range label="Content width" value={Number(s.contentWidth ?? 620)} min={320} max={900} onChange={value=>set('contentWidth',value)}/><Range label="Height" value={Number(s.minHeight ?? 640)} min={360} max={900} onChange={value=>set('minHeight',value)}/></div><Toggle label="Full bleed" value={s.fullBleed !== false} onChange={value=>set('fullBleed',value)}/><Toggle label="Content box" value={Boolean(s.contentBox)} onChange={value=>set('contentBox',value)}/></SectionPanel></>}

    {(section.type==='product_grid'||section.type==='product_carousel'||section.type==='featured_product'||section.type==='product_recommendations')&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Subheading" value={s.subheading} onChange={value=>set('subheading',value)}/>{section.type==='featured_product'&&<Select label="Product" value={s.productId || ''} options={products.map(p=>({value:p.id,label:p.name}))} onChange={value=>set('productId',value)}/>} {section.type!=='featured_product'&&<Select label="Collection" value={s.collection || ''} options={[{value:'',label:'All products'},...collections.map(c=>({value:c.slug||c.id,label:c.name}))]} onChange={value=>set('collection',value)}/>}<div className="themeInspectorGrid"><Range label="Product limit" value={Number(s.limit ?? 8)} min={1} max={48} onChange={value=>set('limit',value)}/><Range label="Columns" value={Number(s.columns ?? 4)} min={2} max={6} onChange={value=>set('columns',value)}/></div><Toggle label="Show View all" value={s.showViewAll !== false} onChange={value=>set('showViewAll',value)}/></SectionPanel><SectionPanel title="Card display"><div className="themeInspectorGrid"><Select label="Card style" value={s.style || 'cards'} options={['cards','minimal','editorial']} onChange={value=>set('style',value)}/><Select label="Image ratio" value={s.imageRatio || 'square'} options={['square','portrait','landscape']} onChange={value=>set('imageRatio',value)}/></div></SectionPanel></>}

    {(section.type==='collection_grid'||section.type==='collection_carousel')&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Subheading" value={s.subheading} onChange={value=>set('subheading',value)}/><Range label="Collections shown" value={Number(s.limit ?? 4)} min={1} max={24} onChange={value=>set('limit',value)}/><Range label="Columns" value={Number(s.columns ?? 4)} min={2} max={6} onChange={value=>set('columns',value)}/></SectionPanel><SectionPanel title="Collection selection"><Select label="Collection" value={(Array.isArray(s.collectionIds)?s.collectionIds[0]:'') || ''} options={[{value:'',label:'Automatic'},...collections.map(c=>({value:c.id,label:c.name}))]} onChange={value=>set('collectionIds',value?[value]:[])} /></SectionPanel></>}

    {section.type==='image_with_text'&&<><SectionPanel title="Content"><Field label="Eyebrow" value={s.eyebrow} onChange={value=>set('eyebrow',value)}/><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Text" value={s.text} onChange={value=>set('text',value)}/><div className="themeInspectorGrid"><Field label="Button label" value={s.buttonLabel} onChange={value=>set('buttonLabel',value)}/><Field label="Button URL" value={s.buttonUrl} onChange={value=>set('buttonUrl',value)}/></div></SectionPanel><SectionPanel title="Media & layout"><Field label="Image URL" value={s.imageUrl} onChange={value=>set('imageUrl',value)}/><Select label="Image position" value={s.layout || 'image-right'} options={['image-left','image-right']} onChange={value=>set('layout',value)}/><Select label="Background" value={s.background || 'secondary'} options={['default','secondary','surface','dark']} onChange={value=>set('background',value)}/><Range label="Min height" value={Number(s.minHeight ?? 420)} min={260} max={700} onChange={value=>set('minHeight',value)}/></SectionPanel></>}

    {section.type==='promo_grid'&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><Range label="Columns" value={Number(s.columns ?? 3)} min={2} max={4} onChange={value=>set('columns',value)}/></SectionPanel><SectionPanel title="Promo cards"><BlocksEditor section={section} type="promo" onUpdateBlocks={onUpdateBlocks}/></SectionPanel></>}
    {section.type==='testimonials'&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Subheading" value={s.subheading} onChange={value=>set('subheading',value)}/><Range label="Columns" value={Number(s.columns ?? 3)} min={1} max={4} onChange={value=>set('columns',value)}/><Toggle label="Autoplay" value={s.autoplay !== false} onChange={value=>set('autoplay',value)}/></SectionPanel><SectionPanel title="Testimonials"><BlocksEditor section={section} type="quote" onUpdateBlocks={onUpdateBlocks}/></SectionPanel></>}
    {section.type==='newsletter'&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Text" value={s.text} onChange={value=>set('text',value)}/><Field label="Button label" value={s.buttonLabel} onChange={value=>set('buttonLabel',value)}/></SectionPanel><SectionPanel title="Appearance"><Select label="Background" value={s.background || 'primary'} options={['primary','secondary','surface','dark']} onChange={value=>set('background',value)}/></SectionPanel></>}
    {(section.type==='rich_text'||section.type==='main_collection_banner')&&<><SectionPanel title="Content"><Field label="Eyebrow" value={s.eyebrow} onChange={value=>set('eyebrow',value)}/><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Text" value={s.text} onChange={value=>set('text',value)}/><Field label="Button label" value={s.buttonLabel} onChange={value=>set('buttonLabel',value)}/><Field label="Button URL" value={s.buttonUrl} onChange={value=>set('buttonUrl',value)}/></SectionPanel>{addCommonLayout()}</>}

    {section.type==='multicolumn'&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Subheading" value={s.subheading} onChange={value=>set('subheading',value)}/><Range label="Columns" value={Number(s.columns ?? 3)} min={2} max={4} onChange={value=>set('columns',value)}/></SectionPanel><SectionPanel title="Columns"><BlocksEditor section={section} type="column" onUpdateBlocks={onUpdateBlocks}/></SectionPanel></>}
    {section.type==='faq'&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><TextArea label="Subheading" value={s.subheading} onChange={value=>set('subheading',value)}/></SectionPanel><SectionPanel title="Questions"><BlocksEditor section={section} type="question" onUpdateBlocks={onUpdateBlocks}/></SectionPanel></>}
    {section.type==='logo_list'&&<><SectionPanel title="Content"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><Range label="Columns" value={Number(s.columns ?? 4)} min={2} max={6} onChange={value=>set('columns',value)}/></SectionPanel><SectionPanel title="Logos"><BlocksEditor section={section} type="logo" onUpdateBlocks={onUpdateBlocks}/></SectionPanel></>}

    {section.type==='announcement'&&<SectionPanel title="Announcement"><Toggle label="Enabled" value={s.enabled !== false} onChange={value=>set('enabled',value)}/><Field label="Text" value={s.text} onChange={value=>set('text',value)}/><Field label="Link URL" value={s.link} onChange={value=>set('link',value)}/><div className="themeInspectorGrid"><Range label="Height" value={Number(s.height ?? 40)} min={28} max={72} onChange={value=>set('height',value)}/><Range label="Speed" value={Number(s.speed ?? 6)} min={1} max={15} onChange={value=>set('speed',value)}/></div><Toggle label="Dismissible" value={s.dismissible !== false} onChange={value=>set('dismissible',value)}/><Toggle label="Show icon" value={Boolean(s.showIcon)} onChange={value=>set('showIcon',value)}/><Toggle label="Uppercase" value={Boolean(s.uppercase)} onChange={value=>set('uppercase',value)}/></SectionPanel>}
    {section.type==='header'&&<SectionPanel title="Header"><Select label="Style" value={s.style || 'split'} options={['split','centered','minimal']} onChange={value=>set('style',value)}/><Toggle label="Sticky" value={s.sticky !== false} onChange={value=>set('sticky',value)}/><Toggle label="Search" value={s.showSearch !== false} onChange={value=>set('showSearch',value)}/><Toggle label="Account" value={s.showAccount !== false} onChange={value=>set('showAccount',value)}/><Toggle label="Cart" value={s.showCart !== false} onChange={value=>set('showCart',value)}/><Toggle label="Mega menu" value={s.megaMenu !== false} onChange={value=>set('megaMenu',value)}/><Range label="Logo width" value={Number(s.logoWidth ?? 160)} min={80} max={260} onChange={value=>set('logoWidth',value)}/><Range label="Navigation spacing" value={Number(s.navSpacing ?? 24)} min={8} max={56} onChange={value=>set('navSpacing',value)}/></SectionPanel>}
    {section.type==='footer'&&<SectionPanel title="Footer"><Toggle label="Newsletter" value={s.showNewsletter !== false} onChange={value=>set('showNewsletter',value)}/><TextArea label="Footer text" value={s.text} onChange={value=>set('text',value)}/><Range label="Columns" value={Number(s.columns ?? 4)} min={2} max={5} onChange={value=>set('columns',value)}/></SectionPanel>}
    {(section.type==='video'||section.type==='slideshow')&&<SectionPanel title={section.type==='video'?'Video':'Slideshow'}><Field label="Media URL" value={s.imageUrl || s.videoUrl} onChange={value=>set(section.type==='video'?'videoUrl':'imageUrl',value)}/><Field label="Poster image" value={s.posterUrl || s.imageUrl} onChange={value=>set(section.type==='video'?'posterUrl':'imageUrl',value)}/>{section.type==='slideshow'&&<BlocksEditor section={section} type="slide" onUpdateBlocks={onUpdateBlocks}/>}<Toggle label="Autoplay" value={s.autoplay !== false} onChange={value=>set('autoplay',value)}/><Range label="Height" value={Number(s.minHeight ?? 560)} min={320} max={860} onChange={value=>set('minHeight',value)}/></SectionPanel>}

    {(section.type==='main_product'||section.type==='main_collection_grid')&&<SectionPanel title="Template section"><Field label="Heading" value={s.heading} onChange={value=>set('heading',value)}/><Range label="Columns" value={Number(s.columns ?? 4)} min={2} max={6} onChange={value=>set('columns',value)}/><Range label="Product limit" value={Number(s.limit ?? 24)} min={1} max={48} onChange={value=>set('limit',value)}/><Toggle label="Show shipping information" value={s.showShipping !== false} onChange={value=>set('showShipping',value)}/></SectionPanel>}

    {!['hero','product_grid','product_carousel','featured_product','product_recommendations','collection_grid','collection_carousel','image_with_text','promo_grid','testimonials','newsletter','rich_text','main_collection_banner','multicolumn','faq','logo_list','announcement','header','footer','video','slideshow','main_product','main_collection_grid'].includes(section.type)&&addCommonLayout()}
  </div>
}
