'use client'
import {useEffect,useMemo,useState} from 'react'
import {ArrowDown,ArrowLeft,ArrowUp,Copy,Eye,GripVertical,Image as ImageIcon,Monitor,Palette,Plus,Redo2,Save,Search,Settings2,Smartphone,Tablet,Trash2,Undo2,X} from 'lucide-react'
import StorefrontSections from '@/components/storefront-sections'
import styles from './shopify-theme-editor-v2.module.css'

type S={id:string;type:string;enabled?:boolean;settings?:Record<string,any>;blocks?:any[]};type T=Record<string,any>;type Snap={theme:T;template:string;sections:S[];navigation:any[]}
const templates=['Home page','Products','Product','Collections','Collection','Cart','Pages','Blog']
const meta:Record<string,{label:string;cat:string;desc:string}>=
{hero:{label:'Image banner',cat:'Hero & media',desc:'Large visual hero with copy and calls to action.'},slideshow:{label:'Slideshow',cat:'Hero & media',desc:'Rotating campaign slides.'},video:{label:'Video',cat:'Hero & media',desc:'Featured video or poster image.'},image_with_text:{label:'Image with text',cat:'Hero & media',desc:'Editorial split image and copy.'},product_grid:{label:'Featured collection',cat:'Products',desc:'Product grid from your catalog.'},product_carousel:{label:'Featured collection carousel',cat:'Products',desc:'Scrollable product collection.'},featured_product:{label:'Featured product',cat:'Products',desc:'Single product spotlight.'},product_recommendations:{label:'Product recommendations',cat:'Products',desc:'Related products for product pages.'},collection_grid:{label:'Collection list',cat:'Collections',desc:'Visual collection cards.'},collection_carousel:{label:'Collection carousel',cat:'Collections',desc:'Scrollable collection cards.'},main_collection_banner:{label:'Collection banner',cat:'Collections',desc:'Collection title and introduction.'},main_collection_grid:{label:'Collection products',cat:'Collections',desc:'Main collection product grid.'},rich_text:{label:'Rich text',cat:'Content',desc:'Text-led editorial section.'},multicolumn:{label:'Multicolumn',cat:'Content',desc:'Benefits, features or editorial cards.'},testimonials:{label:'Testimonials',cat:'Content',desc:'Customer reviews and social proof.'},faq:{label:'Collapsible content',cat:'Content',desc:'Expandable questions and answers.'},logo_list:{label:'Logo list',cat:'Content',desc:'Brands, partners or press logos.'},newsletter:{label:'Email signup banner',cat:'Content',desc:'Newsletter call to action.'},announcement:{label:'Announcement bar',cat:'Header',desc:'Shipping and promotion notice.'},header:{label:'Header',cat:'Header',desc:'Store navigation and customer actions.'},footer:{label:'Footer',cat:'Footer',desc:'Footer navigation and policies.'}}
const picker=Object.keys(meta).filter(k=>!['announcement','header','footer'].includes(k));const clone=<U,>(v:U):U=>structuredClone(v)
function fallback(k:string,src:S[]):S[]{if(k==='Home page')return src;if(k==='Product')return[{id:'ann',type:'announcement',enabled:true,settings:{text:'Free shipping on orders over $50'}},{id:'head',type:'header',enabled:true,settings:{}},{id:'prod',type:'main_product',enabled:true,settings:{}},{id:'rec',type:'product_recommendations',enabled:true,settings:{heading:'You may also like',limit:4,columns:4}},{id:'foot',type:'footer',enabled:true,settings:{}}];if(k==='Collection')return[{id:'ann',type:'announcement',enabled:true,settings:{text:'Free shipping on orders over $50'}},{id:'head',type:'header',enabled:true,settings:{}},{id:'ban',type:'main_collection_banner',enabled:true,settings:{heading:'Collection'}},{id:'grid',type:'main_collection_grid',enabled:true,settings:{heading:'Products',limit:24,columns:4}},{id:'foot',type:'footer',enabled:true,settings:{}}];return[{id:k+'-intro',type:'rich_text',enabled:true,settings:{eyebrow:k.toUpperCase(),heading:k,text:'Build this page from the sections below.'}},{id:k+'-products',type:'product_grid',enabled:true,settings:{heading:'Featured products',limit:8,columns:4}},{id:k+'-foot',type:'footer',enabled:true,settings:{}}]}
const title=(t:string)=>meta[t]?.label||t.replaceAll('_',' ')
export default function ShopifyThemeEditorV2({initial}:{initial:{theme:T;sections:S[];navigation:any[]}}){
 const [theme,setTheme]=useState<T>(()=>clone(initial.theme||{})),[nav,setNav]=useState<any[]>(()=>clone(initial.navigation||[])),[template,setTemplate]=useState('Home page'),[sections,setSections]=useState<S[]>(()=>clone(initial.sections||[])),[selectedId,setSelectedId]=useState(initial.sections?.[0]?.id||''),[device,setDevice]=useState<'desktop'|'tablet'|'mobile'>('desktop'),[drawer,setDrawer]=useState(false),[pickerOpen,setPickerOpen]=useState(false),[query,setQuery]=useState(''),[settingsOpen,setSettingsOpen]=useState(false),[history,setHistory]=useState<Snap[]>([]),[future,setFuture]=useState<Snap[]>([]),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[dragId,setDragId]=useState<string|null>(null),[products,setProducts]=useState<any[]>([]),[collections,setCollections]=useState<any[]>([])
 const selected=useMemo(()=>sections.find(x=>x.id===selectedId)||null,[sections,selectedId]),idx=useMemo(()=>sections.findIndex(x=>x.id===selectedId),[sections,selectedId])
 useEffect(()=>{let a=true;Promise.all([fetch('/api/products',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[]),fetch('/api/admin/collections',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[])]).then(([p,c])=>{if(!a)return;setProducts(Array.isArray(p)?p:[]);setCollections(Array.isArray(c)?c:[])});return()=>{a=false}},[])
 useEffect(()=>{let a=true;const load=async()=>{try{const r=await fetch('/api/navigation',{cache:'no-store'});const d=await r.json();if(a&&Array.isArray(d.navigation))setNav(d.navigation)}catch{}};void load();const tm=setInterval(load,3000);window.addEventListener('focus',load);return()=>{a=false;clearInterval(tm);window.removeEventListener('focus',load)}},[])
 const snap=():Snap=>({theme:clone(theme),template,sections:clone(sections),navigation:clone(nav)}),mutate=(fn:(s:Snap)=>Snap)=>{const before=snap(),after=fn(clone(before));setHistory(h=>[...h,before].slice(-50));setFuture([]);setTheme(after.theme);setTemplate(after.template);setSections(after.sections);setNav(after.navigation);setDirty(true)}
 const switchTemplate=(next:string)=>{const et={...(theme.editorTemplates||{}),[template]:clone(sections)};const target=clone(et[next]||fallback(next,initial.sections||[]));setTheme({...theme,editorTemplates:et});setTemplate(next);setSections(target);setSelectedId(target[0]?.id||'');setDrawer(false);setSettingsOpen(false);setDirty(false)}
 const save=async()=>{setSaving(true);setNotice('');setError('');const et={...(theme.editorTemplates||{}),[template]:clone(sections)},nt={...theme,editorTemplates:et},home=clone(template==='Home page'?sections:(et['Home page']||initial.sections||[]));try{const r=await fetch('/api/admin/theme',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({theme:nt,sections:home,navigation:nav})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to save');setTheme(nt);setDirty(false);setNotice('Saved · storefront synced');try{const c=new BroadcastChannel('store-theme');c.postMessage({theme:nt,sections:home});c.close()}catch{}try{const c=new BroadcastChannel('store-navigation');c.postMessage({navigation:nav});c.close()}catch{}}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setSaving(false)}}
 const update=(patch:Record<string,any>)=>{if(!selected)return;mutate(s=>({...s,sections:s.sections.map(x=>x.id===selected.id?{...x,settings:{...(x.settings||{}),...patch}}:x)}))}
 const add=(type:string)=>{const n:S={id:type+'-'+Date.now(),type,enabled:true,settings:type==='hero'?{eyebrow:'NEW COLLECTION',heading:'Make your store impossible to ignore.',text:'A premium storefront built for conversion.',buttonLabel:'Shop now',buttonUrl:'/shop',imageUrl:'',minHeight:520}:{heading:title(type),subheading:'',limit:type.includes('product')?8:4,columns:4,spacing:72},blocks:[]};mutate(s=>{const a=[...s.sections];a.splice(idx>=0?idx+1:a.length,0,n);return{...s,sections:a}});setSelectedId(n.id);setDrawer(true);setPickerOpen(false);setQuery('')}
 const remove=()=>{if(!selected)return;const a=sections.filter(x=>x.id!==selected.id);mutate(s=>({...s,sections:a}));setSelectedId(a[Math.max(0,idx-1)]?.id||a[0]?.id||'');setDrawer(false)}
 const dup=()=>{if(!selected)return;const c=clone(selected);c.id=c.type+'-'+Date.now();mutate(s=>{const a=[...s.sections];a.splice(idx+1,0,c);return{...s,sections:a}});setSelectedId(c.id)}
 const move=(d:number)=>{if(idx<0)return;mutate(s=>{const a=[...s.sections],n=idx+d;if(n<0||n>=a.length)return s;[a[idx],a[n]]=[a[n],a[idx]];return{...s,sections:a}})}
 const toggle=(id:string)=>mutate(s=>({...s,sections:s.sections.map(x=>x.id===id?{...x,enabled:x.enabled===false}:x)}))
 const drop=(target:string)=>{if(!dragId||dragId===target)return;const from=sections.findIndex(x=>x.id===dragId),to=sections.findIndex(x=>x.id===target);if(from<0||to<0)return;mutate(s=>{const a=[...s.sections],[it]=a.splice(from,1);a.splice(to,0,it);return{...s,sections:a}});setDragId(null)}
 const undo=()=>{if(!history.length)return;const p=history[history.length-1];setFuture(f=>[...f,snap()]);setHistory(h=>h.slice(0,-1));setTheme(p.theme);setTemplate(p.template);setSections(p.sections);setNav(p.navigation);setDirty(true)}
 const redo=()=>{if(!future.length)return;const n=future[future.length-1];setHistory(h=>[...h,snap()]);setFuture(f=>f.slice(0,-1));setTheme(n.theme);setTemplate(n.template);setSections(n.sections);setNav(n.navigation);setDirty(true)}
 const visible=sections.filter(s=>s.enabled!==false&&!['announcement','header','footer'].includes(s.type)),groups=useMemo(()=>{const q=query.toLowerCase();return['Hero & media','Products','Collections','Content'].map(cat=>({cat,items:picker.filter(k=>meta[k].cat===cat&&(!q||meta[k].label.toLowerCase().includes(q)))})).filter(x=>x.items.length)},[query])
 return <div className={styles.t2Editor}>
  <header className={styles.t2Top}><div className={styles.t2TopLeft}><a className={styles.t2Back} href="/admin/online-store"><ArrowLeft size={16}/></a><div><div className={styles.t2Eyebrow}>ONLINE STORE</div><div className={styles.t2Title}>Theme editor</div></div></div><div className={styles.t2Template}><span className={styles.t2Eyebrow}>Template</span><select value={template} onChange={e=>switchTemplate(e.target.value)}>{templates.map(t=><option key={t}>{t}</option>)}</select></div><div className={styles.t2TopRight}>{dirty&&<span className={styles.t2Dirty}><i/>Unsaved</span>}<button className={styles.t2IconBtn} disabled={!history.length} onClick={undo}><Undo2 size={15}/></button><button className={styles.t2IconBtn} disabled={!future.length} onClick={redo}><Redo2 size={15}/></button><div className={styles.t2Devices}><button className={device==='desktop'?styles.active:''} onClick={()=>setDevice('desktop')}><Monitor size={14}/></button><button className={device==='tablet'?styles.active:''} onClick={()=>setDevice('tablet')}><Tablet size={14}/></button><button className={device==='mobile'?styles.active:''} onClick={()=>setDevice('mobile')}><Smartphone size={14}/></button></div><button className={styles.t2Action} onClick={()=>window.open('/','_blank','noopener,noreferrer')}><Eye size={14}/>View live</button><button className={styles.t2Action+' '+styles.accent} onClick={save} disabled={saving}><Save size={14}/>{saving?'Saving…':'Save'}</button></div></header>
  <div className={styles.t2Body}>
   <aside className={styles.t2Sidebar}><div className={styles.t2SidebarHead}><div><div className={styles.t2Eyebrow}>{template}</div><h2>Sections</h2><p>{sections.filter(x=>x.enabled!==false).length} visible · {sections.length} total</p></div><button className={styles.t2IconBtn} onClick={()=>setPickerOpen(true)}><Plus size={15}/></button></div>
    <div className={styles.t2SectionList}>{sections.map(x=><div key={x.id} className={styles.t2SectionItem+' '+(selectedId===x.id?styles.selected:'')+' '+(x.enabled===false?styles.hidden:'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop(x.id)}}><button className={styles.t2Drag} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',x.id);setDragId(x.id)}} onDragEnd={()=>setDragId(null)}><GripVertical size={16}/></button><button className={styles.t2SectionMain} onClick={()=>{setSelectedId(x.id);setDrawer(true)}}><strong>{title(x.type)}</strong><span>{x.enabled===false?'Hidden':'Visible'}</span></button><button className={styles.t2Mini} onClick={()=>toggle(x.id)}>{x.enabled===false?'○':'•'}</button></div>)}</div>
    <button className={styles.t2AddWide} onClick={()=>setPickerOpen(true)}><Plus size={15}/>Add section</button><div className={styles.t2QuickLinks}><a href="/admin/online-store/navigation"><Settings2 size={14}/>Navigation</a><a href="/admin/media"><ImageIcon size={14}/>Media library</a></div><div style={{padding:12}}><button className={styles.t2Action} style={{width:'100%',justifyContent:'center'}} onClick={()=>setSettingsOpen(v=>!v)}><Palette size={14}/>{settingsOpen?'Back to sections':'Theme settings'}</button></div>{settingsOpen&&<ThemeSettings theme={theme} update={p=>mutate(s=>({...s,theme:{...s.theme,...p}}))}/>}<div className={styles.t2SaveState}>{dirty?'Changes are local until saved.':'Saved storefront state.'}</div></aside>
   <main className={styles.t2Preview}><div className={styles.t2PreviewBar}><div><span className={styles.t2Eyebrow}>LIVE PREVIEW</span> <strong>{template}</strong></div><span className={styles.t2PreviewBadge}><i/>{nav.length?'Navigation synced':'No menu items'}</span></div><div className={styles.t2Canvas}><div className={styles.t2Device+' '+(device==='tablet'?styles.tablet:device==='mobile'?styles.mobile:'')}><div className={styles.t2StoreChrome}><div className={styles.t2StoreAnnouncement}>{theme.announcement?.text||'Free shipping on orders over $50'}</div><header className={styles.t2StoreHeader}><div className={styles.t2StoreLogo}>{theme.logoUrl?<img src={theme.logoUrl} alt={theme.brandName||''}/>:theme.brandName||'YALLA HAUL'}</div><nav className={styles.t2StoreNav}>{nav.slice(0,6).map((n:any)=><span key={n.id}>{n.label}</span>)}</nav><div className={styles.t2StoreActions}>⌕ ♡ 🛍</div></header><StorefrontSections theme={theme} sections={visible} products={products} collections={collections} preview selectedId={selectedId} onSelect={id=>{setSelectedId(id);setDrawer(true)}}/></div></div></div></main>
   {drawer&&selected&&<aside className={styles.t2Inspector}><div className={styles.t2InspectorHead}><div><div className={styles.t2Eyebrow}>SECTION</div><h2>{title(selected.type)}</h2></div><div className={styles.t2InspectorTools}><button className={styles.t2IconBtn} onClick={()=>move(-1)} disabled={idx<=0}><ArrowUp size={14}/></button><button className={styles.t2IconBtn} onClick={()=>move(1)} disabled={idx>=sections.length-1}><ArrowDown size={14}/></button><button className={styles.t2IconBtn} onClick={dup}><Copy size={14}/></button><button className={styles.t2IconBtn} onClick={remove}><Trash2 size={14}/></button><button className={styles.t2IconBtn} onClick={()=>setDrawer(false)}><X size={14}/></button></div></div><Inspector section={selected} update={update}/></aside>}
  </div>
  {pickerOpen&&<div className={styles.t2Modal} onMouseDown={e=>{if(e.target===e.currentTarget)setPickerOpen(false)}}><div className={styles.t2Picker}><div className={styles.t2PickerHead}><strong>Add section</strong><button onClick={()=>setPickerOpen(false)}><X size={15}/></button></div><div className={styles.t2Search}><Search size={14}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sections…"/></div><div className={styles.t2PickerScroll}>{groups.map(g=><div className={styles.t2Category} key={g.cat}><span>{g.cat}</span>{g.items.map(k=><button className={styles.t2Option} key={k} onClick={()=>add(k)}><span><strong>{meta[k].label}</strong><small>{meta[k].desc}</small></span><Plus size={15}/></button>)}</div>)}</div></div></div>}
  {notice&&<div className={styles.t2Toast}>{notice}</div>}{error&&<div className={styles.t2Toast+' '+styles.error}>{error}</div>}
 </div>
}
function Inspector({section,update}:{section:S;update:(p:Record<string,any>)=>void}){const s=section.settings||{};const F=(l:string,k:string,v:any=s[k]??'')=><div className={styles.t2Field}><label>{l}</label><input value={String(v)} onChange={e=>update({[k]:e.target.value})}/></div>;const A=(l:string,k:string,v:any=s[k]??'')=><div className={styles.t2Field}><label>{l}</label><textarea value={String(v)} onChange={e=>update({[k]:e.target.value})}/></div>;return <div className={styles.t2InspectorBody}><details className={styles.t2Panel} open><summary>Content</summary><div className={styles.t2PanelBody}>{F('Eyebrow','eyebrow')}{F('Heading','heading')}{A('Text','text',s.text??s.subheading)}{['hero','image_with_text'].includes(section.type)&&<>{F('Button label','buttonLabel')}{F('Button URL','buttonUrl')}{F('Image URL','imageUrl')}</>}{section.type==='announcement'&&<>{F('Message','text')}{F('Link','link')}</>}{section.type==='video'&&<>{F('Poster image','imageUrl')}{F('Video URL','url')}</>}{section.type==='newsletter'&&<Select label="Style" value={s.background||'primary'} options={['primary','secondary','surface','dark']} onChange={v=>update({background:v})}/>} {(section.type.includes('product')||section.type.includes('collection'))&&<div className={styles.t2Grid2}><Range label="Items" value={Number(s.limit||8)} min={1} max={24} step={1} onChange={v=>update({limit:v})}/><Range label="Columns" value={Number(s.columns||4)} min={1} max={6} step={1} onChange={v=>update({columns:v})}/></div>}</div></details><details className={styles.t2Panel} open><summary>Design</summary><div className={styles.t2PanelBody}><Range label="Section spacing" value={Number(s.spacing||72)} min={0} max={160} step={4} onChange={v=>update({spacing:v})}/>{section.type==='hero'&&<Range label="Hero height" value={Number(s.minHeight||520)} min={320} max={760} step={10} onChange={v=>update({minHeight:v})}/>}</div></details></div>}
function ThemeSettings({theme,update}:{theme:T;update:(p:Record<string,any>)=>void}){const c=theme.colors||{},ty=theme.typography||{},l=theme.layout||{};return <div className={styles.t2InspectorBody}><details className={styles.t2Panel} open><summary>Brand</summary><div className={styles.t2PanelBody}><Field l="Brand name" v={theme.brandName||''} u={p=>update(p)}/><Field l="Logo URL" v={theme.logoUrl||''} u={p=>update(p)}/></div></details><details className={styles.t2Panel} open><summary>Colors</summary><div className={styles.t2PanelBody}><div className={styles.t2Grid2}><Color label="Primary" value={c.primary||'#ff5a1f'} onChange={v=>update({colors:{...c,primary:v}})}/><Color label="Background" value={c.background||'#fffaf6'} onChange={v=>update({colors:{...c,background:v}})}/><Color label="Text" value={c.text||'#191512'} onChange={v=>update({colors:{...c,text:v}})}/><Color label="Surface" value={c.surface||'#fff'} onChange={v=>update({colors:{...c,surface:v}})}/></div></div></details><details className={styles.t2Panel} open><summary>Typography</summary><div className={styles.t2PanelBody}><Select label="Heading" value={ty.heading||'Inter'} options={['Inter','Manrope','DM Sans','Poppins','Georgia','Playfair Display']} onChange={v=>update({typography:{...ty,heading:v}})}/><Select label="Body" value={ty.body||'Inter'} options={['Inter','Manrope','DM Sans','Poppins','Arial','Georgia']} onChange={v=>update({typography:{...ty,body:v}})}/></div></details><details className={styles.t2Panel} open><summary>Layout</summary><div className={styles.t2PanelBody}><Range label="Store width" value={Number(l.maxWidth||1360)} min={960} max={1680} step={10} onChange={v=>update({layout:{...l,maxWidth:v}})}/></div></details></div>}
function Field({l,v,u}:{l:string;v:string;u:(p:Record<string,any>)=>void}){const k=l==='Brand name'?'brandName':'logoUrl';return <div className={styles.t2Field}><label>{l}</label><input value={v} onChange={e=>u({[k]:e.target.value})}/></div>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <div className={styles.t2Field}><label>{label}</label><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></div>}
function Range({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void}){return <div className={styles.t2Range}><div className={styles.t2RangeTop}><span>{label}</span><b>{value}</b></div><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></div>}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className={styles.t2Field}><label>{label}</label><div style={{display:'grid',gridTemplateColumns:'42px 1fr',gap:8}}><input type="color" value={value} onChange={e=>onChange(e.target.value)} style={{padding:4,height:40}}/><input value={value} onChange={e=>onChange(e.target.value)}/></div></div>}
