'use client'
import Link from 'next/link'
import {Search,ShoppingBag,UserRound,ChevronDown,Menu,X} from 'lucide-react'
import {useMemo,useState} from 'react'
import {useCart} from './cart-provider'
export function StoreNav({theme,navigation}:{theme:any;navigation:any[]}){const {count}=useCart();const [open,setOpen]=useState(false);const tree=useMemo(()=>navigation.filter((x:any)=>!x.parentId).map((x:any)=>({...x,children:[...navigation.filter((c:any)=>c.parentId===x.id)]})),[navigation]);const announcement=theme.announcement.enabled?<div className={`announcementBar announcement-${theme.announcement.position||'above'} ${theme.announcement.autoplay?'announcementMarquee':''} ${theme.announcement.uppercase?'announcementUpper':''}`} style={{background:theme.colors.announcementBg,color:theme.colors.announcementText,minHeight:theme.announcement.height||40}}><div className="announcementInner container"><span className="announcementMessage">{theme.announcement.showIcon&&<span className="announcementIcon">✦</span>}{theme.announcement.text}</span>{theme.announcement.link&&<Link href={theme.announcement.link}>Learn more</Link>}</div></div>:null;return <>
{theme.announcement.position!=='below'&&announcement}
<header className="nav" style={{background:theme.colors.surface,borderColor:theme.colors.border,position:theme.header.sticky?'sticky':'relative'}}><div className="container navInner" style={{maxWidth:theme.layout.maxWidth,gridTemplateColumns:theme.header.style==='centered'?'1fr auto 1fr':'auto 1fr auto'}}><button className="mobileMenu iconBtn" onClick={()=>setOpen(true)}><Menu size={18}/></button><Link href="/" className="logo" style={{fontFamily:theme.typography.heading}}>{theme.logoUrl?<img src={theme.logoUrl} alt={theme.brandName} className="navLogoImg" style={{maxWidth:theme.header.logoWidth||160}}/>:theme.brandName}</Link><nav className="navLinks">{tree.map((item:any)=><div className="navItem" key={item.id}>{item.children?.length?<><button className="navDropBtn">{item.label}<ChevronDown size={14}/></button><div className="navDropdown">{item.children.map((child:any)=><Link href={child.url||'#'} key={child.id}>{child.label}</Link>)}</div></>:<Link href={item.url||'#'}>{item.label}</Link>}</div>)}</nav><div className="navActions">{theme.header.showSearch&&<Link className="iconBtn" href="/shop" aria-label="Search"><Search size={18}/></Link>}{theme.header.showAccount&&<Link className="iconBtn" href="/account" aria-label="Account"><UserRound size={18}/></Link>}{theme.header.showCart&&<Link className="iconBtn" href="/cart" aria-label={`Cart with ${count} items`}><ShoppingBag size={18}/>{count>0&&<span className="cartBadge">{count>99?'99+':count}</span>}</Link>}</div></div></header>
{theme.announcement.position==='below'&&announcement}
{open&&<div className="mobileDrawer"><button className="iconBtn" onClick={()=>setOpen(false)}><X/></button><div className="mobileMenuLinks">{tree.map((item:any)=><div key={item.id}><Link href={item.url||'#'} onClick={()=>setOpen(false)}>{item.label}</Link>{item.children?.map((c:any)=><Link className="sub" href={c.url||'#'} key={c.id} onClick={()=>setOpen(false)}>{c.label}</Link>)}</div>)}</div></div>}
</>}
