import {db} from '@/lib/prisma'
import {getThemeState} from '@/lib/theme'
import {notFound} from 'next/navigation'
import {Footer} from '@/components/footer'
import {ProductPurchase} from '@/components/product-purchase'
import {ReviewForm} from '@/components/review-form'
import ProductGallery from '@/components/product-gallery'
import {ProductCard} from '@/components/product-card'
import Link from 'next/link'
import {Share2,Heart} from 'lucide-react'

export default async function ProductPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params
 const {theme}=await getThemeState()
 const p=await db.product.findUnique({where:{slug},include:{images:{orderBy:{sortOrder:'asc'}},category:true,variants:{include:{inventory:true}},reviews:{where:{approved:true},include:{user:{select:{name:true}}},orderBy:{createdAt:'desc'},take:12}}})
 if(!p||p.status!=='ACTIVE')return notFound()
 const template=Array.isArray((theme as any).editorTemplates?.Product)&&((theme as any).editorTemplates.Product as any[]).length?(theme as any).editorTemplates.Product as any[]:[{id:'announcement',type:'announcement',enabled:true,settings:{text:theme.announcement?.text||'Free shipping on orders over $50',background:'primary'}},{id:'main_product',type:'main_product',enabled:true,settings:{}},{id:'product_recommendations',type:'product_recommendations',enabled:true,settings:{heading:'You may also like',limit:Number(theme.productPage?.relatedLimit||4),columns:4}},{id:'newsletter',type:'newsletter',enabled:true,settings:{}},{id:'footer',type:'footer',enabled:true,settings:{}}]
 const variants=p.variants.map(v=>({id:v.id,name:v.name,sku:v.sku,price:v.price,compareAtPrice:v.compareAtPrice,stock:v.inventory.reduce((a,x)=>a+Math.max(0,x.quantity-x.reserved),0)}))
 const related=p.category?await db.product.findMany({where:{status:'ACTIVE',categoryId:p.categoryId,id:{not:p.id}},include:{images:true,category:true},take:12,orderBy:{featured:'desc'}}):[]
 const mainProduct=(sec:any)=><section className="section productPage"><div className="container">{theme.productPage?.showBreadcrumbs!==false&&<div className="breadcrumbs"><Link href="/shop">Shop</Link><span>/</span>{p.category&&<><Link href={`/shop?category=${p.category.slug}`}>{p.category.name}</Link><span>/</span></>}<span>{p.name}</span></div>}<div className={`productLayout gallery-${theme.productPage?.gallery||'left'}`}><ProductGallery images={p.images} name={p.name}/><div className={`productInfo ${theme.productPage?.stickyInfo?'stickyInfo':''}`}>{theme.productPage?.showVendor!==false&&<div className="muted uppercase">{p.vendor||p.category?.name||'PRODUCT'}</div>}<h1>{p.name}</h1>{theme.productPage?.showReviews!==false&&<div className="productRating">{'★'.repeat(Math.round(p.reviews.length?p.reviews.reduce((s,r)=>s+r.rating,0)/p.reviews.length:0))}{p.reviews.length>0&&<span>{p.reviews.length} reviews</span>}</div>}<p className="productLead">{p.shortDescription||p.description||''}</p><ProductPurchase productId={p.id} name={p.name} sku={p.sku} basePrice={p.basePrice} compareAtPrice={p.compareAtPrice} image={p.images[0]?.url} variants={variants}/><div className="productActionRow">{theme.productPage?.showWishlist!==false&&<button className="btn secondary"><Heart size={16}/> Wishlist</button>}{theme.productPage?.showShare!==false&&<button className="btn secondary"><Share2 size={16}/> Share</button>}</div><div className="productDetailsAcc">{theme.productPage?.showDescription!==false&&<details open><summary>Description</summary><div className="richProductText">{p.description||p.shortDescription||'No description yet.'}</div></details>}{theme.productPage?.showShippingAccordion!==false&&<details><summary>Shipping & returns</summary><div className="richProductText">Shipping rates and delivery estimates are calculated at checkout. Returns follow your store policy.</div></details>}{theme.productPage?.showSpecs!==false&&<details><summary>Product information</summary><div className="productSpecGrid"><span>SKU</span><strong>{p.sku}</strong><span>Category</span><strong>{p.category?.name||'—'}</strong>{p.weight&&<><span>Weight</span><strong>{p.weight} {p.weightUnit||'kg'}</strong></>}</div></details>}</div></div></div>{theme.productPage?.showReviews!==false&&<section className="productReviews"><div className="sectionHead"><div><span className="muted">CUSTOMER REVIEWS</span><h2 className="h2">What customers think</h2></div></div>{!p.reviews.length?<p className="muted">No reviews yet.</p>:<div className="reviewGrid">{p.reviews.map(r=><article className="reviewCard" key={r.id}><div className="reviewStars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><strong>{r.title||'Verified review'}</strong><p>{r.body}</p><span className="muted">{r.user.name}</span></article>)}</div>}<ReviewForm productId={p.id}/></section>}</div></section>
 const recommendations=(sec:any)=><section className="section relatedProducts"><div className="container"><div className="sectionHead"><div><span className="muted">YOU MAY ALSO LIKE</span><h2 className="h2">{sec.settings?.heading||'Related products'}</h2></div><Link href={p.category?`/shop?category=${p.category.slug}`:'/shop'} className="btn secondary">View all</Link></div><div className="grid productGrid">{related.slice(0,Number(sec.settings?.limit||4)).map(r=><ProductCard key={r.id} p={r}/>)}</div></div></section>
 const rich=(sec:any)=><section className="section"><div className="container"><span className="muted">{sec.settings?.eyebrow||'ABOUT THE STORE'}</span><h2 className="h2">{sec.settings?.heading||''}</h2><p className="body muted">{sec.settings?.text||''}</p></div></section>
 const newsletter=(sec:any)=><section className="section"><div className="container"><div className={`newsletterHome ${sec.settings?.background||'primary'}`}><div><span className="muted">NEWSLETTER</span><h2 className="h2">{sec.settings?.heading||'Stay in the loop'}</h2><p className="muted">{sec.settings?.text||''}</p></div></div></div></section>
 return <><main>{template.filter((sec:any)=>sec.enabled!==false&&sec.type!=='header').map((sec:any)=>sec.type==='announcement'?<section key={sec.id} className="storeSection announcementSection" style={{padding:0,background:sec.settings?.background==='secondary'?theme.colors.secondary:theme.colors.primary,color:sec.settings?.textColor||'#fff'}}><div className="announcementBar"><div className="announcementInner container">{sec.settings?.text||'Free shipping on orders over $50'}</div></div></section>:sec.type==='main_product'||sec.type==='featured_product'?<div key={sec.id}>{mainProduct(sec)}</div>:sec.type==='product_recommendations'?<div key={sec.id}>{recommendations(sec)}</div>:sec.type==='rich_text'?<div key={sec.id}>{rich(sec)}</div>:sec.type==='newsletter'?<div key={sec.id}>{newsletter(sec)}</div>:sec.type==='footer'?<Footer key={sec.id}/>:null)}</main></>
}
